idf_component_register(SRCS
        "main.cpp"
        "tts_audio.cpp"
        "ui.c"
        "ui_comp_hook.c"
        "ui_helpers.c"
        "ui_HOME.c"
        "ui_HOUR.c"
        "ui_MENU.c"
        "ui_SETTINGS.c"
        "ui_PIAMSYS.c"
        "ui_SOS.c"
        "ui_CALCULATOR.c"
        "ui_CRONOS.c"
        "ui_WordYPhra.c"
        "ui_KEYBOARD.c"
        "ui_font_DESIGNER25.c"
        "ui_font_DESIGNER36.c"
        "ui_font_DESIGNER100.c"
        "ui_font_Font28.c"
        "ui_font_Font100.c"
        "ui_font_Font50.c"
        "ui_font_Font20.c"
        "ui_img_piam_home_png.c"
        "ui_img_keyboard_png.c"
        "ui_img_talk_png.c"
        "ui_img_sing_png.c"
        "ui_img_add_png.c"
        "ui_img_editar_png.c"
        "ui_img_singer_png.c"
    INCLUDE_DIRS ".")

target_compile_options(${COMPONENT_LIB} PRIVATE -Wno-error=enum-compare)
