// This file was generated by SquareLine Vision Exporter
// Project name: PIAM Pro

#ifndef _GUI_H
#define _GUI_H

#include "core/gui_core.h"

#include "core/variables.h"

#include "helpers/ui_helpers.h"

LV_IMG_DECLARE(upload_piam_home_png);
LV_FONT_DECLARE(Bebas120);

#endif
