// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#ifndef UI_CALCULATOR_H
#define UI_CALCULATOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CALCULATOR
extern void ui_CALCULATOR_screen_init(void);
extern void ui_CALCULATOR_screen_destroy(void);
extern void ui_event_CALCULATOR(lv_event_t * e);
extern lv_obj_t * ui_CALCULATOR;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

