// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#ifndef UI_CRONOS_H
#define UI_CRONOS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CRONOS
extern void ui_CRONOS_screen_init(void);
extern void ui_CRONOS_screen_destroy(void);
extern void ui_event_CRONOS(lv_event_t * e);
extern lv_obj_t * ui_CRONOS;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_MicroSecLabel;
extern lv_obj_t * ui_SecondLabel;
extern lv_obj_t * ui_MinuteLabel;
extern lv_obj_t * ui_DobleDot;
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label21;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

