// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#ifndef UI_HOUR_H
#define UI_HOUR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HOUR
extern void ui_HOUR_screen_init(void);
extern void ui_HOUR_screen_destroy(void);
extern lv_obj_t * ui_HOUR;
extern void ui_event_Container1(lv_event_t * e);
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

