// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HOME
extern void ui_HOME_screen_init(void);
extern void ui_HOME_screen_destroy(void);
extern void ui_event_HOME(lv_event_t * e);
extern lv_obj_t * ui_HOME;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Bar1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

