// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#include "ui.h"

lv_obj_t * ui_HOME = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Bar1 = NULL;
// event funtions
void ui_event_HOME(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        IncrementBar_Animation(ui_Bar1, 0);
        _ui_screen_change(&ui_HOUR, LV_SCR_LOAD_ANIM_NONE, 0, 7000, &ui_HOUR_screen_init);
    }
}

// build funtions

void ui_HOME_screen_init(void)
{
    ui_HOME = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_HOME, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_HOME);
    lv_image_set_src(ui_Image1, &ui_img_piam_home_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -20);
    lv_obj_set_y(ui_Image1, -18);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image1, 150);
    lv_obj_set_style_image_recolor(ui_Image1, lv_color_hex(0x43E093), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Image1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_HOME);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 0);
    lv_obj_set_height(ui_Bar1, 15);
    lv_obj_set_x(ui_Bar1, 78);
    lv_obj_set_y(ui_Bar1, 93);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x39BA94), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x39BA94), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar1,
                                                                                           lv_obj_get_style_pad_right(ui_Bar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_HOME, ui_event_HOME, LV_EVENT_ALL, NULL);

}

void ui_HOME_screen_destroy(void)
{
    if(ui_HOME) lv_obj_del(ui_HOME);

    // NULL screen variables
    ui_HOME = NULL;
    ui_Image1 = NULL;
    ui_Bar1 = NULL;

}
