// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#include "ui.h"
#include "tts_audio.h"

lv_obj_t * ui_KEYBOARD = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
// event funtions
void ui_event_KEYBOARD(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_PIAMSYS, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_PIAMSYS_screen_init);
    }
}

// build funtions

// PIAM Pro: se dispara al apretar "Enter" en el teclado. Reproduce el
// texto escrito por voz y limpia el cuadro de texto.
void ui_event_Keyboard1_ready(lv_event_t * e)
{
    const char *text = lv_textarea_get_text(ui_TextArea2);
    if (text != NULL && text[0] != '\0') {
        tts_speak(text);
    }
    lv_textarea_set_text(ui_TextArea2, "");
}

void ui_KEYBOARD_screen_init(void)
{
    ui_KEYBOARD = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_KEYBOARD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_KEYBOARD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KEYBOARD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_KEYBOARD);
    lv_obj_set_width(ui_Keyboard1, 395);
    lv_obj_set_height(ui_Keyboard1, 145);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 61);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Keyboard1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x89A0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0xB2CBFD), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Keyboard1, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x768DB9), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Keyboard1, lv_color_hex(0xF6F6F6), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_CHECKED);

    // PIAM Pro: texto mas chico y separacion entre teclas
    lv_obj_set_style_text_font(ui_Keyboard1, &lv_font_montserrat_10, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Keyboard1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Keyboard1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_KEYBOARD);
    lv_obj_set_width(ui_TextArea2, 395);
    lv_obj_set_height(ui_TextArea2, 90);
    lv_obj_set_x(ui_TextArea2, 0);
    lv_obj_set_y(ui_TextArea2, -70);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");
    lv_obj_set_style_bg_color(ui_TextArea2, lv_color_hex(0x5C81C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea2);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1_ready, LV_EVENT_READY, NULL);
    lv_obj_add_event_cb(ui_KEYBOARD, ui_event_KEYBOARD, LV_EVENT_ALL, NULL);

}

void ui_KEYBOARD_screen_destroy(void)
{
    if(ui_KEYBOARD) lv_obj_del(ui_KEYBOARD);

    // NULL screen variables
    ui_KEYBOARD = NULL;
    ui_Keyboard1 = NULL;
    ui_TextArea2 = NULL;

}
