// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#ifndef UI_KEYBOARD_H
#define UI_KEYBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_KEYBOARD
extern void ui_KEYBOARD_screen_init(void);
extern void ui_KEYBOARD_screen_destroy(void);
extern void ui_event_KEYBOARD(lv_event_t * e);
extern lv_obj_t * ui_KEYBOARD;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_TextArea2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

