// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#include "ui.h"

lv_obj_t * ui_MENU = NULL;
lv_obj_t * ui_CronosButton = NULL;
lv_obj_t * ui_PaintButton = NULL;
lv_obj_t * ui_CalcButton = NULL;
lv_obj_t * ui_SOSButton = NULL;
lv_obj_t * ui_SetButton = NULL;
lv_obj_t * ui_PSButton = NULL;
lv_obj_t * ui_OpenMenu = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Bar2 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_CronosButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CRONOS, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_CRONOS_screen_init);
    }
}

void ui_event_CalcButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CALCULATOR, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_CALCULATOR_screen_init);
    }
}

void ui_event_SOSButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SOS, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_SOS_screen_init);
    }
}

void ui_event_SetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SETTINGS, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_SETTINGS_screen_init);
    }
}

void ui_event_PSButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PIAMSYS, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_PIAMSYS_screen_init);
    }
}

void ui_event_OpenMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OpenSET_Animation(ui_SetButton, 0);
        OpenSOS_Animation(ui_SOSButton, 0);
        OpenCALC_Animation(ui_CalcButton, 0);
        OpenPaint_Animation(ui_PaintButton, 0);
        OpenCRONOS_Animation(ui_CronosButton, 0);
        OpenPS_Animation(ui_PSButton, 0);
        CloseOM_Animation(ui_OpenMenu, 0);
    }
}

// build funtions

void ui_MENU_screen_init(void)
{
    ui_MENU = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MENU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MENU, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MENU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CronosButton = lv_button_create(ui_MENU);
    lv_obj_set_width(ui_CronosButton, 75);
    lv_obj_set_height(ui_CronosButton, 75);
    lv_obj_set_x(ui_CronosButton, -203);
    lv_obj_set_y(ui_CronosButton, -123);
    lv_obj_set_align(ui_CronosButton, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_CronosButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CronosButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CronosButton, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CronosButton, lv_color_hex(0x60FFAE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CronosButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CronosButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CronosButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PaintButton = lv_button_create(ui_MENU);
    lv_obj_set_width(ui_PaintButton, 75);
    lv_obj_set_height(ui_PaintButton, 75);
    lv_obj_set_x(ui_PaintButton, 202);
    lv_obj_set_y(ui_PaintButton, -123);
    lv_obj_set_align(ui_PaintButton, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_PaintButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PaintButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PaintButton, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PaintButton, lv_color_hex(0xDF40EC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PaintButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PaintButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PaintButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalcButton = lv_button_create(ui_MENU);
    lv_obj_set_width(ui_CalcButton, 75);
    lv_obj_set_height(ui_CalcButton, 75);
    lv_obj_set_x(ui_CalcButton, -203);
    lv_obj_set_y(ui_CalcButton, 0);
    lv_obj_set_align(ui_CalcButton, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_CalcButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CalcButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CalcButton, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CalcButton, lv_color_hex(0xFF6063), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalcButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CalcButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CalcButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOSButton = lv_button_create(ui_MENU);
    lv_obj_set_width(ui_SOSButton, 75);
    lv_obj_set_height(ui_SOSButton, 75);
    lv_obj_set_x(ui_SOSButton, 203);
    lv_obj_set_y(ui_SOSButton, 0);
    lv_obj_set_align(ui_SOSButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SOSButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SOSButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SOSButton, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SOSButton, lv_color_hex(0x8810CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOSButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SOSButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SOSButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetButton = lv_button_create(ui_MENU);
    lv_obj_set_width(ui_SetButton, 75);
    lv_obj_set_height(ui_SetButton, 75);
    lv_obj_set_x(ui_SetButton, 0);
    lv_obj_set_y(ui_SetButton, 123);
    lv_obj_set_align(ui_SetButton, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_SetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SetButton, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SetButton, lv_color_hex(0x1023CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SetButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SetButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSButton = lv_button_create(ui_MENU);
    lv_obj_set_align(ui_PSButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PSButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PSButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PSButton, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSButton, lv_color_hex(0x0EFFE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PSButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PSButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OpenMenu = lv_button_create(ui_MENU);
    lv_obj_set_width(ui_OpenMenu, 90);
    lv_obj_set_height(ui_OpenMenu, 90);
    lv_obj_set_align(ui_OpenMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OpenMenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_OpenMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_OpenMenu, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OpenMenu, lv_color_hex(0x6D6D6D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OpenMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_OpenMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_OpenMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_OpenMenu);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "+");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x939593), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_MENU);
    lv_bar_set_value(ui_Bar2, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 75);
    lv_obj_set_height(ui_Bar2, 35);
    lv_obj_set_x(ui_Bar2, -35);
    lv_obj_set_y(ui_Bar2, 25);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x99D3A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x08FF4A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar2,
                                                                                           lv_obj_get_style_pad_right(ui_Bar2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label4 = lv_label_create(ui_Bar2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "50");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_DESIGNER25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_MENU);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 90);
    lv_obj_set_height(ui_Container2, 40);
    lv_obj_set_x(ui_Container2, 35);
    lv_obj_set_y(ui_Container2, 25);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x69B480), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "00 : 00");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_CronosButton, ui_event_CronosButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalcButton, ui_event_CalcButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SOSButton, ui_event_SOSButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetButton, ui_event_SetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PSButton, ui_event_PSButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OpenMenu, ui_event_OpenMenu, LV_EVENT_ALL, NULL);

}

void ui_MENU_screen_destroy(void)
{
    if(ui_MENU) lv_obj_del(ui_MENU);

    // NULL screen variables
    ui_MENU = NULL;
    ui_CronosButton = NULL;
    ui_PaintButton = NULL;
    ui_CalcButton = NULL;
    ui_SOSButton = NULL;
    ui_SetButton = NULL;
    ui_PSButton = NULL;
    ui_OpenMenu = NULL;
    ui_Label3 = NULL;
    ui_Bar2 = NULL;
    ui_Label4 = NULL;
    ui_Container2 = NULL;
    ui_Label5 = NULL;

}
