// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#ifndef UI_PIAMSYS_H
#define UI_PIAMSYS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PIAMSYS
extern void ui_PIAMSYS_screen_init(void);
extern void ui_PIAMSYS_screen_destroy(void);
extern void ui_event_PIAMSYS(lv_event_t * e);
extern lv_obj_t * ui_PIAMSYS;
extern void ui_event_KEYButton(lv_event_t * e);
extern lv_obj_t * ui_KEYButton;
extern lv_obj_t * ui_Image3;
extern void ui_event_WorYPhrButton(lv_event_t * e);
extern lv_obj_t * ui_WorYPhrButton;
extern lv_obj_t * ui_Image4;
extern void ui_event_MicButton(lv_event_t * e);
extern lv_obj_t * ui_MicButton;
extern lv_obj_t * ui_Image5;
extern void ui_event_MicPanel(lv_event_t * e);
extern lv_obj_t * ui_MicPanel;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_CancelButton5;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_AceptButton5;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_RecordButton;
extern lv_obj_t * ui_Image7;
extern void ui_event_Placeholder(lv_event_t * e);
extern lv_obj_t * ui_Placeholder;
extern lv_obj_t * ui_Label34;
extern void ui_event_Label43(lv_event_t * e);
extern lv_obj_t * ui_Label43;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

