// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#include "ui.h"
#include "tts_audio.h"

lv_obj_t * ui_PIAMSYS = NULL;
lv_obj_t * ui_KEYButton = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_WorYPhrButton = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_MicButton = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_MicPanel = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_CancelButton5 = NULL;
lv_obj_t * ui_Label42 = NULL;
lv_obj_t * ui_AceptButton5 = NULL;
lv_obj_t * ui_Label41 = NULL;
lv_obj_t * ui_RecordButton = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Placeholder = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_CancelButton4 = NULL;
lv_obj_t * ui_Label43 = NULL;
// event funtions
void ui_event_PIAMSYS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_MENU, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_MENU_screen_init);
    }
}

void ui_event_KEYButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_KEYBOARD, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_KEYBOARD_screen_init);
    }
}

void ui_event_WorYPhrButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WordYPhra, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_WordYPhra_screen_init);
    }
}

void ui_event_MicButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_MicPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_MicPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_flag_modify(ui_MicPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Placeholder(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_flag_modify(ui_Placeholder, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// ======================= PIAM Pro: STT (Speech to Text) =======================

// RecordButton (checkable, verde->rojo). Al chequear, arranca a grabar.
// Al deschequear, corta la grabacion y la manda a transcribir -- y
// se BLOQUEA (ya no se puede clickear/chequear) hasta que se resuelva
// con Aceptar o Cancelar.
void ui_event_RecordButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        bool checked = lv_obj_has_state(ui_RecordButton, LV_STATE_CHECKED);

        if (checked) {
            stt_start_recording();
        } else {
            stt_stop_and_transcribe();
            // Bloquear el boton: ya se grabo una vez, hay que resolver
            // con Aceptar o Cancelar antes de poder grabar de nuevo.
            lv_obj_remove_flag(ui_RecordButton, LV_OBJ_FLAG_CLICKABLE);
        }
    }
}

// Muestra el texto transcripto en el panel de resultado (Placeholder).
void ui_event_AceptButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        lv_label_set_text(ui_Label34, stt_get_last_transcript());
        lv_obj_remove_flag(ui_Placeholder, LV_OBJ_FLAG_HIDDEN);
    }
}

// Descarta todo: cierra el panel del microfono completo y resetea
// RecordButton para la proxima vez.
void ui_event_CancelButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        lv_obj_remove_state(ui_RecordButton, LV_STATE_CHECKED);
        lv_obj_add_flag(ui_RecordButton, LV_OBJ_FLAG_CLICKABLE);
        lv_obj_add_flag(ui_MicPanel, LV_OBJ_FLAG_HIDDEN);
    }
}

// Cierra el panel de transcripcion (Placeholder) Y todo el panel del
// microfono, dejando todo reseteado para la proxima vez.
void ui_event_CancelButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        lv_obj_add_flag(ui_Placeholder, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_state(ui_RecordButton, LV_STATE_CHECKED);
        lv_obj_add_flag(ui_RecordButton, LV_OBJ_FLAG_CLICKABLE);
        lv_obj_add_flag(ui_MicPanel, LV_OBJ_FLAG_HIDDEN);
    }
}

// ================================================================================

// build funtions

void ui_PIAMSYS_screen_init(void)
{
    ui_PIAMSYS = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_PIAMSYS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PIAMSYS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PIAMSYS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KEYButton = lv_button_create(ui_PIAMSYS);
    lv_obj_set_width(ui_KEYButton, 211);
    lv_obj_set_height(ui_KEYButton, 78);
    lv_obj_set_x(ui_KEYButton, -68);
    lv_obj_set_y(ui_KEYButton, -42);
    lv_obj_set_align(ui_KEYButton, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_KEYButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_KEYButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_KEYButton, lv_color_hex(0x5C81C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KEYButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_KEYButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_KEYButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_KEYButton);
    lv_image_set_src(ui_Image3, &ui_img_keyboard_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -1);
    lv_obj_set_y(ui_Image3, 3);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Image3, LV_STATE_DISABLED);       /// States
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image3, 200);
    lv_obj_set_style_radius(ui_Image3, 900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WorYPhrButton = lv_button_create(ui_PIAMSYS);
    lv_obj_set_width(ui_WorYPhrButton, 214);
    lv_obj_set_height(ui_WorYPhrButton, 139);
    lv_obj_set_x(ui_WorYPhrButton, -68);
    lv_obj_set_y(ui_WorYPhrButton, 44);
    lv_obj_set_align(ui_WorYPhrButton, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_WorYPhrButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_WorYPhrButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WorYPhrButton, lv_color_hex(0x4AC2BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WorYPhrButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WorYPhrButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WorYPhrButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_WorYPhrButton);
    lv_image_set_src(ui_Image4, &ui_img_talk_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Image4, LV_STATE_DISABLED);       /// States
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image4, 200);
    lv_obj_set_style_radius(ui_Image4, 900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MicButton = lv_button_create(ui_PIAMSYS);
    lv_obj_set_width(ui_MicButton, 118);
    lv_obj_set_height(ui_MicButton, 235);
    lv_obj_set_x(ui_MicButton, 65);
    lv_obj_set_y(ui_MicButton, 0);
    lv_obj_set_align(ui_MicButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MicButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MicButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MicButton, lv_color_hex(0x48C07D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MicButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_MicButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_MicButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_MicButton);
    lv_image_set_src(ui_Image5, &ui_img_sing_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Image5, LV_STATE_DISABLED);       /// States
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image5, 210);

    ui_MicPanel = lv_obj_create(ui_PIAMSYS);
    lv_obj_set_width(ui_MicPanel, 480);
    lv_obj_set_height(ui_MicPanel, 320);
    lv_obj_set_align(ui_MicPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MicPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_MicPanel, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MicPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MicPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MicPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MicPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_MicPanel);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -107);
    lv_obj_set_y(ui_Label33, -107);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "Micrófono");
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0x4AC27B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label33, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CancelButton5 = lv_button_create(ui_MicPanel);
    lv_obj_set_width(ui_CancelButton5, 125);
    lv_obj_set_height(ui_CancelButton5, 40);
    lv_obj_set_x(ui_CancelButton5, -85);
    lv_obj_set_y(ui_CancelButton5, 115);
    lv_obj_set_align(ui_CancelButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CancelButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CancelButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CancelButton5, lv_color_hex(0x9CC69C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CancelButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CancelButton5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CancelButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_CancelButton5);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "Cancelar");
    lv_obj_set_style_text_font(ui_Label42, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AceptButton5 = lv_button_create(ui_MicPanel);
    lv_obj_set_width(ui_AceptButton5, 125);
    lv_obj_set_height(ui_AceptButton5, 40);
    lv_obj_set_x(ui_AceptButton5, 85);
    lv_obj_set_y(ui_AceptButton5, 115);
    lv_obj_set_align(ui_AceptButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AceptButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_AceptButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AceptButton5, lv_color_hex(0x1F5F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AceptButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AceptButton5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AceptButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AceptButton5, lv_color_hex(0x7A2121), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_AceptButton5, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label41 = lv_label_create(ui_AceptButton5);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "Aceptar");
    lv_obj_set_style_text_font(ui_Label41, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordButton = lv_button_create(ui_MicPanel);
    lv_obj_set_width(ui_RecordButton, 100);
    lv_obj_set_height(ui_RecordButton, 100);
    lv_obj_set_align(ui_RecordButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RecordButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_RecordButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RecordButton, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RecordButton, lv_color_hex(0x198A47), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RecordButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RecordButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RecordButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RecordButton, lv_color_hex(0x972323), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_RecordButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image7 = lv_image_create(ui_RecordButton);
    lv_image_set_src(ui_Image7, &ui_img_singer_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Image7, LV_STATE_DISABLED);       /// States
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Placeholder = lv_obj_create(ui_MicPanel);
    lv_obj_set_width(ui_Placeholder, 390);
    lv_obj_set_height(ui_Placeholder, 270);
    lv_obj_set_align(ui_Placeholder, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Placeholder, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Placeholder, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Placeholder, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Placeholder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Placeholder, lv_color_hex(0x494949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Placeholder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_Placeholder);
    lv_obj_set_width(ui_Label34, 350);
    lv_obj_set_height(ui_Label34, 198);
    lv_label_set_text(ui_Label34, "Placeholder...");
    lv_obj_set_style_text_font(ui_Label34, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CancelButton4 = lv_button_create(ui_Placeholder);
    lv_obj_set_width(ui_CancelButton4, 100);
    lv_obj_set_height(ui_CancelButton4, 35);
    lv_obj_set_x(ui_CancelButton4, 120);
    lv_obj_set_y(ui_CancelButton4, 100);
    lv_obj_set_align(ui_CancelButton4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CancelButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CancelButton4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CancelButton4, lv_color_hex(0x9CC69C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CancelButton4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CancelButton4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CancelButton4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_CancelButton4);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "Cancelar");
    lv_obj_set_style_text_font(ui_Label43, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_KEYButton, ui_event_KEYButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WorYPhrButton, ui_event_WorYPhrButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MicButton, ui_event_MicButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Placeholder, ui_event_Placeholder, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MicPanel, ui_event_MicPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PIAMSYS, ui_event_PIAMSYS, LV_EVENT_ALL, NULL);

    // PIAM Pro: eventos de STT
    lv_obj_add_event_cb(ui_RecordButton, ui_event_RecordButton, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_AceptButton5, ui_event_AceptButton5, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_CancelButton5, ui_event_CancelButton5, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_CancelButton4, ui_event_CancelButton4, LV_EVENT_CLICKED, NULL);

}

void ui_PIAMSYS_screen_destroy(void)
{
    if(ui_PIAMSYS) lv_obj_del(ui_PIAMSYS);

    // NULL screen variables
    ui_PIAMSYS = NULL;
    ui_KEYButton = NULL;
    ui_Image3 = NULL;
    ui_WorYPhrButton = NULL;
    ui_Image4 = NULL;
    ui_MicButton = NULL;
    ui_Image5 = NULL;
    ui_MicPanel = NULL;
    ui_Label33 = NULL;
    ui_CancelButton5 = NULL;
    ui_Label42 = NULL;
    ui_AceptButton5 = NULL;
    ui_Label41 = NULL;
    ui_RecordButton = NULL;
    ui_Image7 = NULL;
    ui_Placeholder = NULL;
    ui_Label34 = NULL;
    ui_CancelButton4 = NULL;
    ui_Label43 = NULL;

}
