// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SETTINGS
extern void ui_SETTINGS_screen_init(void);
extern void ui_SETTINGS_screen_destroy(void);
extern void ui_event_SETTINGS(lv_event_t * e);
extern lv_obj_t * ui_SETTINGS;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

