// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#include "ui.h"

lv_obj_t * ui_SETTINGS = NULL;
// event funtions
void ui_event_SETTINGS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_MENU, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_MENU_screen_init);
    }
}

// build funtions

void ui_SETTINGS_screen_init(void)
{
    ui_SETTINGS = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SETTINGS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SETTINGS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SETTINGS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SETTINGS, ui_event_SETTINGS, LV_EVENT_ALL, NULL);

}

void ui_SETTINGS_screen_destroy(void)
{
    if(ui_SETTINGS) lv_obj_del(ui_SETTINGS);

    // NULL screen variables
    ui_SETTINGS = NULL;

}
