// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#include "ui.h"
#include "esp_pcf85063_port.h"
#include "tts_audio.h"
#include "nvs_flash.h"
#include "nvs.h"
#include <string.h>
#include <stdio.h>

lv_obj_t * ui_SOS = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_AddButton = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_EditButton = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_AddPanel = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Dropdown3 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Dropdown2 = NULL;
lv_obj_t * ui_Button17 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Button18 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_EditPanel = NULL;
// event funtions
void ui_event_SOS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_MENU, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_MENU_screen_init);
    }
}

// ======================= PIAM Pro: motor de alarmas =======================

#define MAX_ALARMS 10

typedef struct {
    uint8_t hour;   // 0-23
    uint8_t minute; // 0-59
    bool enabled;
} piam_alarm_t;

static piam_alarm_t s_alarms[MAX_ALARMS];
static int s_alarm_count = 0;
static int s_editing_index = -1; // -1 = agregando nueva, >=0 = editando esa alarma

static void alarms_load(void)
{
    s_alarm_count = 0;
    nvs_handle_t nvs;
    if (nvs_open("piam_alarms", NVS_READONLY, &nvs) == ESP_OK) {
        size_t size = sizeof(s_alarms);
        nvs_get_blob(nvs, "list", s_alarms, &size);
        int32_t count = 0;
        nvs_get_i32(nvs, "count", &count);
        if (count >= 0 && count <= MAX_ALARMS) s_alarm_count = (int)count;
        nvs_close(nvs);
    }
}

static void alarms_save(void)
{
    nvs_handle_t nvs;
    if (nvs_open("piam_alarms", NVS_READWRITE, &nvs) == ESP_OK) {
        nvs_set_blob(nvs, "list", s_alarms, sizeof(s_alarms));
        nvs_set_i32(nvs, "count", s_alarm_count);
        nvs_commit(nvs);
        nvs_close(nvs);
    }
}

static void format_alarm_time(int hour24, int minute, char *out, size_t out_size)
{
    const char *ampm = (hour24 < 12) ? "AM" : "PM";
    int hour12 = hour24 % 12;
    if (hour12 == 0) hour12 = 12;
    snprintf(out, out_size, "%02d:%02d %s", hour12, minute, ampm);
}

static void ui_event_AlarmRowClicked(lv_event_t * e);
static void ui_event_AlarmSwitchToggled(lv_event_t * e);

// Vuelve a armar la lista visual de alarmas en Panel1, a partir de
// s_alarms. Se llama despues de cargar, agregar, editar o borrar.
static void populate_alarm_list(void)
{
    lv_obj_clean(ui_Panel1);

    for (int i = 0; i < s_alarm_count; i++) {
        lv_obj_t *row = lv_obj_create(ui_Panel1);
        lv_obj_remove_style_all(row);
        lv_obj_set_width(row, 288);
        lv_obj_set_height(row, 50);
        lv_obj_set_style_radius(row, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(row, lv_color_hex(0x3C1756), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(row, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_add_flag(row, LV_OBJ_FLAG_CLICKABLE);

        lv_obj_t *label = lv_label_create(row);
        char buf[16];
        format_alarm_time(s_alarms[i].hour, s_alarms[i].minute, buf, sizeof(buf));
        lv_label_set_text(label, buf);
        lv_obj_set_x(label, -70);
        lv_obj_set_align(label, LV_ALIGN_CENTER);
        lv_obj_set_style_text_color(label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(label, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

        lv_obj_t *sw = lv_switch_create(row);
        lv_obj_set_width(sw, 50);
        lv_obj_set_height(sw, 25);
        lv_obj_set_x(sw, 80);
        lv_obj_set_align(sw, LV_ALIGN_CENTER);
        lv_obj_set_style_bg_color(sw, lv_color_hex(0x8A63A4), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(sw, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(sw, lv_color_hex(0xE900EC), LV_PART_INDICATOR | LV_STATE_CHECKED);
        lv_obj_set_style_bg_opa(sw, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
        if (s_alarms[i].enabled) lv_obj_add_state(sw, LV_STATE_CHECKED);
        lv_obj_set_user_data(sw, (void *)(intptr_t)i);
        lv_obj_add_event_cb(sw, ui_event_AlarmSwitchToggled, LV_EVENT_VALUE_CHANGED, NULL);

        lv_obj_set_user_data(row, (void *)(intptr_t)i);
        lv_obj_add_event_cb(row, ui_event_AlarmRowClicked, LV_EVENT_CLICKED, NULL);
    }
}

// Prendido/apagado individual de una alarma (sin abrir el panel de edicion)
static void ui_event_AlarmSwitchToggled(lv_event_t * e)
{
    lv_obj_t *sw = lv_event_get_target(e);
    int idx = (int)(intptr_t)lv_obj_get_user_data(sw);
    if (idx < 0 || idx >= s_alarm_count) return;

    s_alarms[idx].enabled = lv_obj_has_state(sw, LV_STATE_CHECKED);
    alarms_save();
}

// Click en una alarma existente -> abrir AddPanel pre-cargado con su
// horario, y mostrar el boton de borrar (Button3).
static void ui_event_AlarmRowClicked(lv_event_t * e)
{
    lv_obj_t *row = lv_event_get_target(e);
    int idx = (int)(intptr_t)lv_obj_get_user_data(row);
    if (idx < 0 || idx >= s_alarm_count) return;

    s_editing_index = idx;
    lv_dropdown_set_selected(ui_Dropdown3, s_alarms[idx].hour);
    lv_dropdown_set_selected(ui_Dropdown2, s_alarms[idx].minute);

    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag(ui_AddPanel, LV_OBJ_FLAG_HIDDEN);
}

// ---------------------------------------------------------------------
// Chequeo global: se ejecuta SIEMPRE (sin importar que pantalla este
// abierta), comparando la hora actual del RTC contra las alarmas
// activas. Si coincide, dispara voz + un aviso visual flotante.
// ---------------------------------------------------------------------

static int s_last_triggered_hour = -1;
static int s_last_triggered_minute = -1;

static void alarm_visual_dismiss_cb(lv_event_t * e)
{
    lv_obj_t *box = (lv_obj_t *)lv_event_get_user_data(e);
    lv_obj_del(box);
}

static void show_alarm_visual(void)
{
    lv_obj_t *box = lv_obj_create(lv_layer_top());
    lv_obj_set_size(box, 300, 120);
    lv_obj_center(box);
    lv_obj_set_style_bg_color(box, lv_color_hex(0xB3395A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(box, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(box, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(box, LV_OBJ_FLAG_CLICKABLE);

    lv_obj_t *label = lv_label_create(box);
    lv_label_set_text(label, "¡ALARMA!\n(tocar para cerrar)");
    lv_obj_set_style_text_align(label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_center(label);

    lv_obj_add_event_cb(box, alarm_visual_dismiss_cb, LV_EVENT_CLICKED, box);

    // Parpadeo simple mientras esta en pantalla
    Blink_Animation(box, 0);
}

static void alarm_check_timer_cb(lv_timer_t *timer)
{
    int hour, minute;
    piam_rtc_get_hour_minute(&hour, &minute);

    if (hour == s_last_triggered_hour && minute == s_last_triggered_minute) {
        return; // ya disparamos para este minuto exacto
    }

    for (int i = 0; i < s_alarm_count; i++) {
        if (s_alarms[i].enabled && s_alarms[i].hour == hour && s_alarms[i].minute == minute) {
            s_last_triggered_hour = hour;
            s_last_triggered_minute = minute;
            tts_speak("Alarma");
            show_alarm_visual();
            break;
        }
    }
}

// Llamar UNA vez desde app_main(), despues de que el RTC ya este listo.
// Carga las alarmas guardadas y arranca el chequeo periodico global
// (independiente de que pantalla este abierta).
void ui_alarms_init(void)
{
    alarms_load();
    lv_timer_create(alarm_check_timer_cb, 20000, NULL); // cada 20 segundos
}

// ============================================================================

void ui_event_AddButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        s_editing_index = -1; // agregando nueva, no editando
        lv_dropdown_set_selected(ui_Dropdown3, 0);
        lv_dropdown_set_selected(ui_Dropdown2, 0);
        lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_HIDDEN); // sin borrar en modo "agregar"
        _ui_flag_modify(ui_AddPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_AddPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        if (s_editing_index >= 0 && s_editing_index < s_alarm_count) {
            // Corremos las alarmas siguientes un lugar para atras
            for (int i = s_editing_index; i < s_alarm_count - 1; i++) {
                s_alarms[i] = s_alarms[i + 1];
            }
            s_alarm_count--;
            alarms_save();
            populate_alarm_list();
        }
        s_editing_index = -1;
        _ui_flag_modify(ui_AddPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// PIAM Pro: "Guardar" -- agrega una alarma nueva, o actualiza la que
// se estaba editando.
void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        int hour = lv_dropdown_get_selected(ui_Dropdown3);
        int minute = lv_dropdown_get_selected(ui_Dropdown2);

        if (s_editing_index >= 0 && s_editing_index < s_alarm_count) {
            // Editando una existente
            s_alarms[s_editing_index].hour = hour;
            s_alarms[s_editing_index].minute = minute;
        } else if (s_alarm_count < MAX_ALARMS) {
            // Agregando una nueva
            s_alarms[s_alarm_count].hour = hour;
            s_alarms[s_alarm_count].minute = minute;
            s_alarms[s_alarm_count].enabled = true;
            s_alarm_count++;
        }

        alarms_save();
        populate_alarm_list();

        s_editing_index = -1;
        _ui_flag_modify(ui_AddPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_SOS_screen_init(void)
{
    ui_SOS = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SOS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SOS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_SOS);
    lv_obj_set_width(ui_Panel1, 312);
    lv_obj_set_height(ui_Panel1, 274);
    lv_obj_set_x(ui_Panel1, 60);
    lv_obj_set_y(ui_Panel1, -21);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scrollbar_mode(ui_Panel1, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_Panel1, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x15071E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Panel1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 288);
    lv_obj_set_height(ui_Container4, 50);
    lv_obj_set_x(ui_Container4, -7);
    lv_obj_set_y(ui_Container4, -7);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0x3C1756), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -70);
    lv_obj_set_y(ui_Label6, 0);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "00:00 AM");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Container4);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 80);
    lv_obj_set_y(ui_Switch1, 0);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x8A63A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x8A63A4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0xE900EC), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0xFFC5F6), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_AddButton = lv_button_create(ui_SOS);
    lv_obj_set_width(ui_AddButton, 97);
    lv_obj_set_height(ui_AddButton, 173);
    lv_obj_set_x(ui_AddButton, 28);
    lv_obj_set_y(ui_AddButton, -27);
    lv_obj_set_align(ui_AddButton, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_AddButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_AddButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AddButton, lv_color_hex(0x6C259B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AddButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AddButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AddButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_image_create(ui_AddButton);
    lv_image_set_src(ui_Image6, &ui_img_add_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image6, 150);

    ui_EditButton = lv_button_create(ui_SOS);
    lv_obj_set_width(ui_EditButton, 97);
    lv_obj_set_height(ui_EditButton, 84);
    lv_obj_set_x(ui_EditButton, -163);
    lv_obj_set_y(ui_EditButton, -96);
    lv_obj_set_align(ui_EditButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EditButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_EditButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EditButton, lv_color_hex(0xA555DA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EditButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_EditButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_EditButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_EditButton);
    lv_image_set_src(ui_Image2, &ui_img_editar_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 3);
    lv_obj_set_y(ui_Image2, -3);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image2, 150);

    ui_AddPanel = lv_obj_create(ui_SOS);
    lv_obj_set_width(ui_AddPanel, 480);
    lv_obj_set_height(ui_AddPanel, 320);
    lv_obj_set_align(ui_AddPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AddPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_AddPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AddPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AddPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AddPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AddPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AddPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AddPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_AddPanel);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -75);
    lv_obj_set_y(ui_Label8, -120);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Agregar alarma");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x6A249C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Font50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown3 = lv_dropdown_create(ui_AddPanel);
    lv_dropdown_set_options(ui_Dropdown3,
                            "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23");
    lv_obj_set_width(ui_Dropdown3, 50);
    lv_obj_set_height(ui_Dropdown3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown3, -50);
    lv_obj_set_y(ui_Dropdown3, -30);
    lv_obj_set_align(ui_Dropdown3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown3, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown3, lv_color_hex(0x0B0D3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown3, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_AddPanel);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, -30);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, ":");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown2 = lv_dropdown_create(ui_AddPanel);
    lv_dropdown_set_options(ui_Dropdown2,
                            "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59");
    lv_obj_set_width(ui_Dropdown2, 50);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 50);
    lv_obj_set_y(ui_Dropdown2, -30);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown2, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown2, lv_color_hex(0x080C39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown2, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button17 = lv_button_create(ui_AddPanel);
    lv_obj_set_width(ui_Button17, 100);
    lv_obj_set_height(ui_Button17, 50);
    lv_obj_set_x(ui_Button17, -100);
    lv_obj_set_y(ui_Button17, 90);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button17, lv_color_hex(0x352441), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Button17);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Cancelar");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button18 = lv_button_create(ui_AddPanel);
    lv_obj_set_width(ui_Button18, 100);
    lv_obj_set_height(ui_Button18, 50);
    lv_obj_set_x(ui_Button18, 100);
    lv_obj_set_y(ui_Button18, 90);
    lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button18, lv_color_hex(0xA066C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Button18);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Guardar");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_AddPanel);
    lv_obj_set_width(ui_Button3, 50);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 200);
    lv_obj_set_y(ui_Button3, -125);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xB3395A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "X");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EditPanel = lv_obj_create(ui_SOS);
    lv_obj_remove_style_all(ui_EditPanel);
    lv_obj_set_width(ui_EditPanel, 449);
    lv_obj_set_height(ui_EditPanel, 303);
    lv_obj_set_align(ui_EditPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EditPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_EditPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_EditPanel, lv_color_hex(0xA455DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EditPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EditPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_AddButton, ui_event_AddButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SOS, ui_event_SOS, LV_EVENT_ALL, NULL);

    // PIAM Pro: mostrar las alarmas reales guardadas (en vez del
    // ejemplo fijo "00:00 AM" que traia Container4/Label6/Switch1)
    populate_alarm_list();

}

void ui_SOS_screen_destroy(void)
{
    if(ui_SOS) lv_obj_del(ui_SOS);

    // NULL screen variables
    ui_SOS = NULL;
    ui_Panel1 = NULL;
    ui_Container4 = NULL;
    ui_Label6 = NULL;
    ui_Switch1 = NULL;
    ui_AddButton = NULL;
    ui_Image6 = NULL;
    ui_EditButton = NULL;
    ui_Image2 = NULL;
    ui_AddPanel = NULL;
    ui_Label8 = NULL;
    ui_Dropdown3 = NULL;
    ui_Label9 = NULL;
    ui_Dropdown2 = NULL;
    ui_Button17 = NULL;
    ui_Label7 = NULL;
    ui_Button18 = NULL;
    ui_Label10 = NULL;
    ui_Button3 = NULL;
    ui_Label11 = NULL;
    ui_EditPanel = NULL;

}
