// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#ifndef UI_SOS_H
#define UI_SOS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SOS
extern void ui_SOS_screen_init(void);
extern void ui_SOS_screen_destroy(void);
extern void ui_event_SOS(lv_event_t * e);
extern lv_obj_t * ui_SOS;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_AddButton;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_EditButton;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

