// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#include "ui.h"
#include "tts_audio.h"
#include <string.h>
#include <stdio.h>

lv_obj_t * ui_WordYPhra = NULL;
lv_obj_t * ui_DailyCont = NULL;
lv_obj_t * ui_DailyButton = NULL;
lv_obj_t * ui_FoodCont = NULL;
lv_obj_t * ui_FoodButton = NULL;
lv_obj_t * ui_SocialCont = NULL;
lv_obj_t * ui_SocialButton = NULL;
lv_obj_t * ui_AnimoCont = NULL;
lv_obj_t * ui_AnimoButton = NULL;
lv_obj_t * ui_DailyScreen = NULL;
lv_obj_t * ui_DailyRoller = NULL;
lv_obj_t * ui_AceptarButton = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_AdjRoller = NULL;
lv_obj_t * ui_VerbRoller = NULL;
lv_obj_t * ui_QuantRoller = NULL;
lv_obj_t * ui_PeopleRoller = NULL;
lv_obj_t * ui_CountryRoller = NULL;
lv_obj_t * ui_StateRoller = NULL;
lv_obj_t * ui_CancelButton = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_AceptButton = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_FemButton = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_MascButton = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_FoodScreen = NULL;
lv_obj_t * ui_FoodRoller = NULL;
lv_obj_t * ui_AceptarButton1 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_SocialScreen = NULL;
lv_obj_t * ui_SocialRoller = NULL;
lv_obj_t * ui_AceptarButton3 = NULL;
lv_obj_t * ui_Label36 = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_CancelButton3 = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_AceptButton3 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_NumberButton = NULL;
lv_obj_t * ui_Label40 = NULL;
lv_obj_t * ui_WeekDayRoller = NULL;
lv_obj_t * ui_TimeRoller = NULL;
lv_obj_t * ui_HourRoller = NULL;
lv_obj_t * ui_AskRoller = NULL;
lv_obj_t * ui_AnimoScreen = NULL;
lv_obj_t * ui_AnimoRoller = NULL;
lv_obj_t * ui_AceptarButton2 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_PositionRoller = NULL;
lv_obj_t * ui_BodyRoller = NULL;
lv_obj_t * ui_RutineRoller = NULL;
lv_obj_t * ui_ColorRoller = NULL;
lv_obj_t * ui_SportRoller = NULL;
lv_obj_t * ui_PlaceRoller = NULL;
lv_obj_t * ui_CancelButton2 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_AceptButton2 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Label35 = NULL;
// event funtions
void ui_event_WordYPhra(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_PIAMSYS, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_PIAMSYS_screen_init);
    }
}

void ui_event_DailyButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DailyScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_FoodButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_FoodScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_SocialButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_SocialScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_AnimoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_AnimoScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_DailyScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_flag_modify(ui_DailyScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_FoodScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_flag_modify(ui_FoodScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_SocialScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_flag_modify(ui_SocialScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_AnimoScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_flag_modify(ui_AnimoScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

// ======================= PIAM Pro: COTIDIANO =======================

static void hide_all_daily_subrollers(void)
{
    lv_obj_add_flag(ui_AdjRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_VerbRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_QuantRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_PeopleRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_CountryRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_StateRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_CancelButton, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_AceptButton, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_FemButton, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_MascButton, LV_OBJ_FLAG_HIDDEN);
}

static void show_daily_main(void)
{
    hide_all_daily_subrollers();
    lv_obj_remove_flag(ui_DailyRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag(ui_AceptarButton, LV_OBJ_FLAG_HIDDEN);
}

void ui_event_AceptarButton_daily(lv_event_t * e)
{
    char buf[64];
    lv_roller_get_selected_str(ui_DailyRoller, buf, sizeof(buf));

    lv_obj_add_flag(ui_DailyRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_AceptarButton, LV_OBJ_FLAG_HIDDEN);

    if (strcmp(buf, "Adjetivos") == 0) {
        lv_obj_remove_flag(ui_AdjRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_FemButton, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_MascButton, LV_OBJ_FLAG_HIDDEN);
    } else if (strcmp(buf, "Verbos") == 0) {
        lv_obj_remove_flag(ui_VerbRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_CancelButton, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_AceptButton, LV_OBJ_FLAG_HIDDEN);
    } else if (strcmp(buf, "Cantidad") == 0) {
        lv_obj_remove_flag(ui_QuantRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_CancelButton, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_AceptButton, LV_OBJ_FLAG_HIDDEN);
    } else if (strcmp(buf, "Personas") == 0) {
        lv_obj_remove_flag(ui_PeopleRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_CancelButton, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_AceptButton, LV_OBJ_FLAG_HIDDEN);
    } else if (strcmp(buf, "Nacionalidad") == 0) {
        lv_obj_remove_flag(ui_CountryRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_CancelButton, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_AceptButton, LV_OBJ_FLAG_HIDDEN);
    } else if (strcmp(buf, "Estado civil") == 0) {
        lv_obj_remove_flag(ui_StateRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_CancelButton, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_AceptButton, LV_OBJ_FLAG_HIDDEN);
    } else {
        tts_speak(buf);
        show_daily_main();
    }
}

void ui_event_CancelButton_daily(lv_event_t * e)
{
    show_daily_main();
}

void ui_event_AceptButton_daily(lv_event_t * e)
{
    char buf[64];
    lv_obj_t *active = NULL;

    if (!lv_obj_has_flag(ui_VerbRoller, LV_OBJ_FLAG_HIDDEN)) active = ui_VerbRoller;
    else if (!lv_obj_has_flag(ui_QuantRoller, LV_OBJ_FLAG_HIDDEN)) active = ui_QuantRoller;
    else if (!lv_obj_has_flag(ui_PeopleRoller, LV_OBJ_FLAG_HIDDEN)) active = ui_PeopleRoller;
    else if (!lv_obj_has_flag(ui_CountryRoller, LV_OBJ_FLAG_HIDDEN)) active = ui_CountryRoller;
    else if (!lv_obj_has_flag(ui_StateRoller, LV_OBJ_FLAG_HIDDEN)) active = ui_StateRoller;

    if (active) {
        lv_roller_get_selected_str(active, buf, sizeof(buf));
        tts_speak(buf);
    }

    show_daily_main();
}

static void speak_adj_with_gender(bool femenino)
{
    char buf[64];
    lv_roller_get_selected_str(ui_AdjRoller, buf, sizeof(buf));

    if (femenino) {
        size_t len = strlen(buf);
        if (len > 0 && buf[len - 1] == 'o') {
            buf[len - 1] = 'a';
        }
    }

    tts_speak(buf);
    show_daily_main();
}

void ui_event_FemButton_daily(lv_event_t * e)
{
    speak_adj_with_gender(true);
}

void ui_event_MascButton_daily(lv_event_t * e)
{
    speak_adj_with_gender(false);
}

// ======================= PIAM Pro: COMIDAS =======================
// (Simplificado: FoodRoller ahora es una lista plana de frases, sin
// categorias/sub-rollers. Aceptar habla directo la opcion elegida.)

void ui_event_AceptarButton_food(lv_event_t * e)
{
    char buf[64];
    lv_roller_get_selected_str(ui_FoodRoller, buf, sizeof(buf));
    tts_speak(buf);
}

// ======================= PIAM Pro: SOCIAL =======================

static int s_hour_number = 1;

static void hide_all_social_subrollers(void)
{
    lv_obj_add_flag(ui_WeekDayRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_TimeRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_HourRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_AskRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_CancelButton3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_AceptButton3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_NumberButton, LV_OBJ_FLAG_HIDDEN);
}

static void show_social_main(void)
{
    hide_all_social_subrollers();
    lv_obj_remove_flag(ui_SocialRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag(ui_AceptarButton3, LV_OBJ_FLAG_HIDDEN);
}

void ui_event_AceptarButton_social(lv_event_t * e)
{
    char buf[64];
    lv_roller_get_selected_str(ui_SocialRoller, buf, sizeof(buf));

    lv_obj_add_flag(ui_SocialRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_AceptarButton3, LV_OBJ_FLAG_HIDDEN);

    if (strcmp(buf, "Día de semana...") == 0) {
        lv_obj_remove_flag(ui_WeekDayRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_CancelButton3, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_AceptButton3, LV_OBJ_FLAG_HIDDEN);
    } else if (strcmp(buf, "Tiempo...") == 0) {
        lv_obj_remove_flag(ui_TimeRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_CancelButton3, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_AceptButton3, LV_OBJ_FLAG_HIDDEN);
    } else if (strcmp(buf, "Hora...") == 0) {
        s_hour_number = 1;
        lv_label_set_text(ui_Label40, "1");
        lv_obj_remove_flag(ui_HourRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_NumberButton, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_AceptButton3, LV_OBJ_FLAG_HIDDEN);
    } else if (strcmp(buf, "Consultas...") == 0) {
        lv_obj_remove_flag(ui_AskRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_CancelButton3, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_AceptButton3, LV_OBJ_FLAG_HIDDEN);
    } else {
        tts_speak(buf);
        show_social_main();
    }
}

void ui_event_CancelButton_social(lv_event_t * e)
{
    show_social_main();
}

void ui_event_NumberButton_social(lv_event_t * e)
{
    s_hour_number++;
    if (s_hour_number > 12) s_hour_number = 1;

    char num_buf[4];
    snprintf(num_buf, sizeof(num_buf), "%d", s_hour_number);
    lv_label_set_text(ui_Label40, num_buf);
}

void ui_event_AceptButton_social(lv_event_t * e)
{
    char buf[64];

    if (!lv_obj_has_flag(ui_HourRoller, LV_OBJ_FLAG_HIDDEN)) {
        char roller_txt[48];
        lv_roller_get_selected_str(ui_HourRoller, roller_txt, sizeof(roller_txt));

        if (roller_txt[0] >= 'A' && roller_txt[0] <= 'Z') {
            roller_txt[0] = roller_txt[0] - 'A' + 'a';
        }

        snprintf(buf, sizeof(buf), "Las %d %s", s_hour_number, roller_txt);
        tts_speak(buf);
        show_social_main();
        return;
    }

    lv_obj_t *active = NULL;
    if (!lv_obj_has_flag(ui_WeekDayRoller, LV_OBJ_FLAG_HIDDEN)) active = ui_WeekDayRoller;
    else if (!lv_obj_has_flag(ui_TimeRoller, LV_OBJ_FLAG_HIDDEN)) active = ui_TimeRoller;
    else if (!lv_obj_has_flag(ui_AskRoller, LV_OBJ_FLAG_HIDDEN)) active = ui_AskRoller;

    if (active) {
        lv_roller_get_selected_str(active, buf, sizeof(buf));
        tts_speak(buf);
    }

    show_social_main();
}

// ======================= PIAM Pro: ANIMO =======================

static void hide_all_animo_subrollers(void)
{
    lv_obj_add_flag(ui_PositionRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_BodyRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_RutineRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_ColorRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_SportRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_PlaceRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_CancelButton2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_AceptButton2, LV_OBJ_FLAG_HIDDEN);
}

static void show_animo_main(void)
{
    hide_all_animo_subrollers();
    lv_obj_remove_flag(ui_AnimoRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag(ui_AceptarButton2, LV_OBJ_FLAG_HIDDEN);
}

void ui_event_AceptarButton_animo(lv_event_t * e)
{
    char buf[64];
    lv_roller_get_selected_str(ui_AnimoRoller, buf, sizeof(buf));

    lv_obj_add_flag(ui_AnimoRoller, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_AceptarButton2, LV_OBJ_FLAG_HIDDEN);

    if (strcmp(buf, "Posiciones...") == 0) {
        lv_obj_remove_flag(ui_PositionRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_CancelButton2, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_AceptButton2, LV_OBJ_FLAG_HIDDEN);
    } else if (strcmp(buf, "Cuerpo...") == 0) {
        lv_obj_remove_flag(ui_BodyRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_CancelButton2, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_AceptButton2, LV_OBJ_FLAG_HIDDEN);
    } else if (strcmp(buf, "Rutina diaria...") == 0) {
        lv_obj_remove_flag(ui_RutineRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_CancelButton2, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_AceptButton2, LV_OBJ_FLAG_HIDDEN);
    } else if (strcmp(buf, "Colores...") == 0) {
        lv_obj_remove_flag(ui_ColorRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_CancelButton2, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_AceptButton2, LV_OBJ_FLAG_HIDDEN);
    } else if (strcmp(buf, "Deportes...") == 0) {
        lv_obj_remove_flag(ui_SportRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_CancelButton2, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_AceptButton2, LV_OBJ_FLAG_HIDDEN);
    } else if (strcmp(buf, "Lugares...") == 0) {
        lv_obj_remove_flag(ui_PlaceRoller, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_CancelButton2, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_AceptButton2, LV_OBJ_FLAG_HIDDEN);
    } else {
        tts_speak(buf);
        show_animo_main();
    }
}

void ui_event_CancelButton_animo(lv_event_t * e)
{
    show_animo_main();
}

void ui_event_AceptButton_animo(lv_event_t * e)
{
    char buf[64];
    lv_obj_t *active = NULL;

    if (!lv_obj_has_flag(ui_PositionRoller, LV_OBJ_FLAG_HIDDEN)) active = ui_PositionRoller;
    else if (!lv_obj_has_flag(ui_BodyRoller, LV_OBJ_FLAG_HIDDEN)) active = ui_BodyRoller;
    else if (!lv_obj_has_flag(ui_RutineRoller, LV_OBJ_FLAG_HIDDEN)) active = ui_RutineRoller;
    else if (!lv_obj_has_flag(ui_ColorRoller, LV_OBJ_FLAG_HIDDEN)) active = ui_ColorRoller;
    else if (!lv_obj_has_flag(ui_SportRoller, LV_OBJ_FLAG_HIDDEN)) active = ui_SportRoller;
    else if (!lv_obj_has_flag(ui_PlaceRoller, LV_OBJ_FLAG_HIDDEN)) active = ui_PlaceRoller;

    if (active) {
        lv_roller_get_selected_str(active, buf, sizeof(buf));
        tts_speak(buf);
    }

    show_animo_main();
}

// =====================================================================

void ui_WordYPhra_screen_init(void)
{
    ui_WordYPhra = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WordYPhra, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WordYPhra, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WordYPhra, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DailyCont = lv_obj_create(ui_WordYPhra);
    lv_obj_remove_style_all(ui_DailyCont);
    lv_obj_set_width(ui_DailyCont, 143);
    lv_obj_set_height(ui_DailyCont, 152);
    lv_obj_set_x(ui_DailyCont, -70);
    lv_obj_set_y(ui_DailyCont, -75);
    lv_obj_set_align(ui_DailyCont, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DailyCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DailyButton = lv_arc_create(ui_DailyCont);
    lv_obj_set_width(ui_DailyButton, 275);
    lv_obj_set_height(ui_DailyButton, 275);
    lv_obj_set_x(ui_DailyButton, 71);
    lv_obj_set_y(ui_DailyButton, 74);
    lv_obj_set_align(ui_DailyButton, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DailyButton, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_DailyButton, 99, 100);
    lv_arc_set_value(ui_DailyButton, 100);
    lv_arc_set_bg_angles(ui_DailyButton, 180, 270);
    lv_obj_set_style_arc_color(ui_DailyButton, lv_color_hex(0xFF0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_DailyButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_DailyButton, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_DailyButton, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_DailyButton, lv_color_hex(0xFF2E7C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_arc_opa(ui_DailyButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_arc_width(ui_DailyButton, 70, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_scale(ui_DailyButton, 280, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_x(ui_DailyButton, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_y(ui_DailyButton, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_arc_color(ui_DailyButton, lv_color_hex(0xFF0202), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_DailyButton, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_DailyButton, 70, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_DailyButton, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_DailyButton, lv_color_hex(0xFF2E7C), LV_PART_INDICATOR | LV_STATE_PRESSED);
    lv_obj_set_style_arc_opa(ui_DailyButton, 255, LV_PART_INDICATOR | LV_STATE_PRESSED);
    lv_obj_set_style_arc_width(ui_DailyButton, 70, LV_PART_INDICATOR | LV_STATE_PRESSED);

    lv_obj_set_style_bg_color(ui_DailyButton, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DailyButton, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_FoodCont = lv_obj_create(ui_WordYPhra);
    lv_obj_remove_style_all(ui_FoodCont);
    lv_obj_set_width(ui_FoodCont, 143);
    lv_obj_set_height(ui_FoodCont, 151);
    lv_obj_set_x(ui_FoodCont, 70);
    lv_obj_set_y(ui_FoodCont, -74);
    lv_obj_set_align(ui_FoodCont, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_FoodCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FoodButton = lv_arc_create(ui_FoodCont);
    lv_obj_set_width(ui_FoodButton, 275);
    lv_obj_set_height(ui_FoodButton, 275);
    lv_obj_set_x(ui_FoodButton, -69);
    lv_obj_set_y(ui_FoodButton, 73);
    lv_obj_set_align(ui_FoodButton, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_FoodButton, 99, 100);
    lv_arc_set_value(ui_FoodButton, 100);
    lv_arc_set_bg_angles(ui_FoodButton, 270, 0);
    lv_obj_set_style_arc_color(ui_FoodButton, lv_color_hex(0xFFDF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_FoodButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_FoodButton, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_FoodButton, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_scale(ui_FoodButton, 280, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_x(ui_FoodButton, 200, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_y(ui_FoodButton, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_arc_color(ui_FoodButton, lv_color_hex(0xFFDF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_FoodButton, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_FoodButton, 70, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_FoodButton, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_FoodButton, lv_color_hex(0xFF9840), LV_PART_INDICATOR | LV_STATE_PRESSED);
    lv_obj_set_style_arc_opa(ui_FoodButton, 255, LV_PART_INDICATOR | LV_STATE_PRESSED);

    lv_obj_set_style_bg_color(ui_FoodButton, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FoodButton, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SocialCont = lv_obj_create(ui_WordYPhra);
    lv_obj_remove_style_all(ui_SocialCont);
    lv_obj_set_width(ui_SocialCont, 140);
    lv_obj_set_height(ui_SocialCont, 153);
    lv_obj_set_x(ui_SocialCont, -69);
    lv_obj_set_y(ui_SocialCont, 75);
    lv_obj_set_align(ui_SocialCont, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SocialCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SocialButton = lv_arc_create(ui_SocialCont);
    lv_obj_set_width(ui_SocialButton, 275);
    lv_obj_set_height(ui_SocialButton, 275);
    lv_obj_set_x(ui_SocialButton, 70);
    lv_obj_set_y(ui_SocialButton, -76);
    lv_obj_set_align(ui_SocialButton, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_SocialButton, 99, 100);
    lv_arc_set_value(ui_SocialButton, 100);
    lv_arc_set_bg_angles(ui_SocialButton, 90, 180);
    lv_obj_set_style_arc_color(ui_SocialButton, lv_color_hex(0x00FF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SocialButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SocialButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_SocialButton, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_scale(ui_SocialButton, 280, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_x(ui_SocialButton, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_y(ui_SocialButton, 200, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_arc_color(ui_SocialButton, lv_color_hex(0x00FF24), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SocialButton, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SocialButton, 70, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_SocialButton, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_SocialButton, lv_color_hex(0x2CE49E), LV_PART_INDICATOR | LV_STATE_PRESSED);
    lv_obj_set_style_arc_opa(ui_SocialButton, 255, LV_PART_INDICATOR | LV_STATE_PRESSED);

    lv_obj_set_style_bg_color(ui_SocialButton, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SocialButton, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_AnimoCont = lv_obj_create(ui_WordYPhra);
    lv_obj_remove_style_all(ui_AnimoCont);
    lv_obj_set_width(ui_AnimoCont, 142);
    lv_obj_set_height(ui_AnimoCont, 155);
    lv_obj_set_x(ui_AnimoCont, 71);
    lv_obj_set_y(ui_AnimoCont, 75);
    lv_obj_set_align(ui_AnimoCont, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AnimoCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AnimoButton = lv_arc_create(ui_AnimoCont);
    lv_obj_set_width(ui_AnimoButton, 275);
    lv_obj_set_height(ui_AnimoButton, 275);
    lv_obj_set_x(ui_AnimoButton, -71);
    lv_obj_set_y(ui_AnimoButton, -76);
    lv_obj_set_align(ui_AnimoButton, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_AnimoButton, 99, 100);
    lv_arc_set_value(ui_AnimoButton, 100);
    lv_arc_set_bg_angles(ui_AnimoButton, 0, 90);
    lv_obj_set_style_border_color(ui_AnimoButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AnimoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_AnimoButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_AnimoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AnimoButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AnimoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_AnimoButton, lv_color_hex(0x1010F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_AnimoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_AnimoButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_AnimoButton, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_scale(ui_AnimoButton, 280, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_x(ui_AnimoButton, 200, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_y(ui_AnimoButton, 200, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_border_color(ui_AnimoButton, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AnimoButton, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_AnimoButton, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_AnimoButton, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AnimoButton, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AnimoButton, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_AnimoButton, lv_color_hex(0x1111F2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_AnimoButton, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_AnimoButton, 70, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_AnimoButton, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_AnimoButton, lv_color_hex(0x0084FF), LV_PART_INDICATOR | LV_STATE_PRESSED);
    lv_obj_set_style_arc_opa(ui_AnimoButton, 255, LV_PART_INDICATOR | LV_STATE_PRESSED);

    lv_obj_set_style_bg_color(ui_AnimoButton, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AnimoButton, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_DailyScreen = lv_obj_create(ui_WordYPhra);
    lv_obj_set_width(ui_DailyScreen, 480);
    lv_obj_set_height(ui_DailyScreen, 320);
    lv_obj_set_align(ui_DailyScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DailyScreen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DailyScreen, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DailyScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DailyScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DailyScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DailyScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DailyRoller = lv_roller_create(ui_DailyScreen);
    lv_roller_set_options(ui_DailyRoller,
                          "Sí\nNo\nHola\nBien\nMal\nGracias\nPor favor\nAyuda\nEspera\nBasta\nDolor\nFrío\nCalor\nBaño\nAgua\nAdjetivos\nVerbos\nCantidad\nNinguno\nPersonas\nNacionalidad\nEstado civil",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_DailyRoller, 125);
    lv_obj_set_width(ui_DailyRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_DailyRoller, 0);
    lv_obj_set_y(ui_DailyRoller, -2);
    lv_obj_set_align(ui_DailyRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_DailyRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DailyRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DailyRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DailyRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DailyRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DailyRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DailyRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_DailyRoller, lv_color_hex(0xFF6262), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DailyRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_AceptarButton = lv_button_create(ui_DailyScreen);
    lv_obj_set_width(ui_AceptarButton, 125);
    lv_obj_set_height(ui_AceptarButton, 40);
    lv_obj_set_x(ui_AceptarButton, 146);
    lv_obj_set_y(ui_AceptarButton, 115);
    lv_obj_set_align(ui_AceptarButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AceptarButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_AceptarButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AceptarButton, lv_color_hex(0x924343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AceptarButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AceptarButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AceptarButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_AceptarButton);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Aceptar");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AdjRoller = lv_roller_create(ui_DailyScreen);
    lv_roller_set_options(ui_AdjRoller,
                          "Grande\nChico\nBueno\nMalo\nFeliz\nTriste\nEnojado\nCansado\nNuevo\nViejo\nBlanco\nMoreno\nTrigueño\nRubio\nPelirrojo\nRápido\nLento\nFuerte\nDébil\nFácil\nDifícil\nLimpio\nSucio\nBonito\nFeo\nCaro\nBarato\nDuro\nBlando\nSuave",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_AdjRoller, 125);
    lv_obj_set_width(ui_AdjRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_AdjRoller, 0);
    lv_obj_set_y(ui_AdjRoller, -2);
    lv_obj_set_align(ui_AdjRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AdjRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_AdjRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AdjRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AdjRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AdjRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AdjRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AdjRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AdjRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_AdjRoller, lv_color_hex(0xFF6262), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AdjRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_VerbRoller = lv_roller_create(ui_DailyScreen);
    lv_roller_set_options(ui_VerbRoller,
                          "Querer\nNecesitar\nPoder\nIr\nVenir\nComer\nBeber\nDormir\nJugar\nEstudiar\nTrabajar\nCaminar\nCorrer\nHablar\nEscuchar\nMirar\nLeer\nEscribir\nAbrir\nCerrar\nDar\nTomar\nAyudar\nEsperar\nDescansar",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_VerbRoller, 125);
    lv_obj_set_width(ui_VerbRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_VerbRoller, 0);
    lv_obj_set_y(ui_VerbRoller, -2);
    lv_obj_set_align(ui_VerbRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VerbRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_VerbRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VerbRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VerbRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VerbRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VerbRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VerbRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VerbRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_VerbRoller, lv_color_hex(0xFF6262), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VerbRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_QuantRoller = lv_roller_create(ui_DailyScreen);
    lv_roller_set_options(ui_QuantRoller,
                          "Uno\nDos\nTres\nCuatro\nCinco\nSeis\nSiete\nOcho\nNueve\nDiez\nMás\nMenos\nTodo\nNada\nMucho\nPoco\nAlgunos\nNinguno\nPrimero\nÚltimo\nIgual\nDoble\nMitad\nPar\nGrupo",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_QuantRoller, 125);
    lv_obj_set_width(ui_QuantRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_QuantRoller, 0);
    lv_obj_set_y(ui_QuantRoller, -2);
    lv_obj_set_align(ui_QuantRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_QuantRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_QuantRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_QuantRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_QuantRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_QuantRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_QuantRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_QuantRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_QuantRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_QuantRoller, lv_color_hex(0xFF6262), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_QuantRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_PeopleRoller = lv_roller_create(ui_DailyScreen);
    lv_roller_set_options(ui_PeopleRoller,
                          "Yo\nVos\nÉl\nElla\nNosotros\nMamá\nPapá\nHermano\nHermana\nAbuela\nAbuelo\nTío\nTía\nPrimo\nPrima\nAmigo\nAmiga\nMaestro\nMaestra\nDoctor\nDoctora\nVecino\nVecina\nCompañero\nCompañera",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_PeopleRoller, 125);
    lv_obj_set_width(ui_PeopleRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_PeopleRoller, 0);
    lv_obj_set_y(ui_PeopleRoller, -2);
    lv_obj_set_align(ui_PeopleRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PeopleRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_PeopleRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PeopleRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PeopleRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PeopleRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PeopleRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PeopleRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PeopleRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PeopleRoller, lv_color_hex(0xFF6262), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PeopleRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_CountryRoller = lv_roller_create(ui_DailyScreen);
    lv_roller_set_options(ui_CountryRoller,
                          "Paraguayo\nParaguaya\nArgentino\nArgentina\nBrasileño\nBrasileña\nUruguayo\nUruguaya\nBoliviano\nBoliviana\nChileno\nChilena\nPeruano\nPeruana\nEspañol\nEspañola\nEstadounidense\nMexicano\nMexicana\nColombiano\nColombiana\nExtranjero\nExtranjera",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_CountryRoller, 125);
    lv_obj_set_width(ui_CountryRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_CountryRoller, 0);
    lv_obj_set_y(ui_CountryRoller, -2);
    lv_obj_set_align(ui_CountryRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CountryRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_CountryRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CountryRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CountryRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CountryRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CountryRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CountryRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CountryRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CountryRoller, lv_color_hex(0xFF6262), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CountryRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_StateRoller = lv_roller_create(ui_DailyScreen);
    lv_roller_set_options(ui_StateRoller,
                          "Soltero\nSoltera\nCasado\nCasada\nDivorciado\nDivorciada\nViudo\nViuda\nEn pareja", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_StateRoller, 125);
    lv_obj_set_width(ui_StateRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_StateRoller, 0);
    lv_obj_set_y(ui_StateRoller, -2);
    lv_obj_set_align(ui_StateRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StateRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_StateRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StateRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StateRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StateRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StateRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StateRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StateRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_StateRoller, lv_color_hex(0xFF6262), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StateRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_CancelButton = lv_button_create(ui_DailyScreen);
    lv_obj_set_width(ui_CancelButton, 125);
    lv_obj_set_height(ui_CancelButton, 40);
    lv_obj_set_x(ui_CancelButton, -85);
    lv_obj_set_y(ui_CancelButton, 115);
    lv_obj_set_align(ui_CancelButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CancelButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CancelButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CancelButton, lv_color_hex(0xFF9494), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CancelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CancelButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CancelButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_CancelButton);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Cancelar");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AceptButton = lv_button_create(ui_DailyScreen);
    lv_obj_set_width(ui_AceptButton, 125);
    lv_obj_set_height(ui_AceptButton, 40);
    lv_obj_set_x(ui_AceptButton, 85);
    lv_obj_set_y(ui_AceptButton, 115);
    lv_obj_set_align(ui_AceptButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AceptButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_AceptButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AceptButton, lv_color_hex(0x924343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AceptButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AceptButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AceptButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_AceptButton);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Aceptar");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FemButton = lv_button_create(ui_DailyScreen);
    lv_obj_set_width(ui_FemButton, 100);
    lv_obj_set_height(ui_FemButton, 40);
    lv_obj_set_x(ui_FemButton, -85);
    lv_obj_set_y(ui_FemButton, 115);
    lv_obj_set_align(ui_FemButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FemButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_FemButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FemButton, lv_color_hex(0xFF9494), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FemButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_FemButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_FemButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_FemButton);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "FEM");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MascButton = lv_button_create(ui_DailyScreen);
    lv_obj_set_width(ui_MascButton, 100);
    lv_obj_set_height(ui_MascButton, 40);
    lv_obj_set_x(ui_MascButton, 85);
    lv_obj_set_y(ui_MascButton, 115);
    lv_obj_set_align(ui_MascButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MascButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MascButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MascButton, lv_color_hex(0x924343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MascButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_MascButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_MascButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_MascButton);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "MAsc");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_DailyScreen);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -92);
    lv_obj_set_y(ui_Label14, -112);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Cotidiano");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFF6162), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_DESIGNER36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FoodScreen = lv_obj_create(ui_WordYPhra);
    lv_obj_set_width(ui_FoodScreen, 480);
    lv_obj_set_height(ui_FoodScreen, 320);
    lv_obj_set_align(ui_FoodScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FoodScreen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_FoodScreen, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FoodScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FoodScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FoodScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FoodScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FoodRoller = lv_roller_create(ui_FoodScreen);
    lv_roller_set_options(ui_FoodRoller,
                          "Hambre\nSed\nAgua\nPan\nLeche\nFruta\nCarne\nPollo\nArroz\nSopa\nEnsalada\nPostre\nCafé\nJugo\nMás\nHuevo\nPescado\nQueso\nFideo\nVerdura\nBebida\nComida\nPasta\nCafé\nTé\nMate\nTereré\nGaseosa\nChocolate\nCaramelo\nGalleta\nTorta\nHelado\nFlan\nAlfajor\nTomate\nLechuga\nZanahoria\nPapa\nCebolla\nZapallo\nChoclo",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_FoodRoller, 125);
    lv_obj_set_width(ui_FoodRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_FoodRoller, 0);
    lv_obj_set_y(ui_FoodRoller, -2);
    lv_obj_set_align(ui_FoodRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_FoodRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FoodRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FoodRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FoodRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FoodRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FoodRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FoodRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_FoodRoller, lv_color_hex(0xE0B54D), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FoodRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_AceptarButton1 = lv_button_create(ui_FoodScreen);
    lv_obj_set_width(ui_AceptarButton1, 125);
    lv_obj_set_height(ui_AceptarButton1, 40);
    lv_obj_set_x(ui_AceptarButton1, 146);
    lv_obj_set_y(ui_AceptarButton1, 115);
    lv_obj_set_align(ui_AceptarButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AceptarButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_AceptarButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AceptarButton1, lv_color_hex(0xE6B64A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AceptarButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AceptarButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AceptarButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_AceptarButton1);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Aceptar");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_FoodScreen);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -92);
    lv_obj_set_y(ui_Label25, -112);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Comidas");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xF3C450), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &ui_font_DESIGNER36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SocialScreen = lv_obj_create(ui_WordYPhra);
    lv_obj_set_width(ui_SocialScreen, 480);
    lv_obj_set_height(ui_SocialScreen, 320);
    lv_obj_set_x(ui_SocialScreen, 0);
    lv_obj_set_y(ui_SocialScreen, -2);
    lv_obj_set_align(ui_SocialScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SocialScreen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_SocialScreen, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SocialScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SocialScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SocialScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SocialScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SocialRoller = lv_roller_create(ui_SocialScreen);
    lv_roller_set_options(ui_SocialRoller,
                          "Hola\nBuen día\nBuenas tardes\nBuenas noches\n¿Qué tal?\nMucho gusto\nBienvenido\nEncantado de conocerte\n¡Qué alegría verte!\nAdiós\nChau\nMe voy\nHasta luego\nHasta pronto\nNos vemos\nCuídate\nQue tengas buen día\nDía de semana...\nTiempo...\nHora...\nConsultas...",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_SocialRoller, 125);
    lv_obj_set_width(ui_SocialRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_SocialRoller, 0);
    lv_obj_set_y(ui_SocialRoller, -2);
    lv_obj_set_align(ui_SocialRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_SocialRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SocialRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SocialRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SocialRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SocialRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SocialRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SocialRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SocialRoller, lv_color_hex(0x3FB63F), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SocialRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_AceptarButton3 = lv_button_create(ui_SocialScreen);
    lv_obj_set_width(ui_AceptarButton3, 125);
    lv_obj_set_height(ui_AceptarButton3, 40);
    lv_obj_set_x(ui_AceptarButton3, 146);
    lv_obj_set_y(ui_AceptarButton3, 115);
    lv_obj_set_align(ui_AceptarButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AceptarButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_AceptarButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AceptarButton3, lv_color_hex(0x1F5F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AceptarButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AceptarButton3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AceptarButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_AceptarButton3);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "Aceptar");
    lv_obj_set_style_text_font(ui_Label36, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_SocialScreen);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, -92);
    lv_obj_set_y(ui_Label37, -112);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "Social");
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0x53F350), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &ui_font_DESIGNER36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CancelButton3 = lv_button_create(ui_SocialScreen);
    lv_obj_set_width(ui_CancelButton3, 125);
    lv_obj_set_height(ui_CancelButton3, 40);
    lv_obj_set_x(ui_CancelButton3, -85);
    lv_obj_set_y(ui_CancelButton3, 115);
    lv_obj_set_align(ui_CancelButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CancelButton3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CancelButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CancelButton3, lv_color_hex(0x9CC69C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CancelButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CancelButton3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CancelButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_CancelButton3);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "Cancelar");
    lv_obj_set_style_text_font(ui_Label38, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AceptButton3 = lv_button_create(ui_SocialScreen);
    lv_obj_set_width(ui_AceptButton3, 125);
    lv_obj_set_height(ui_AceptButton3, 40);
    lv_obj_set_x(ui_AceptButton3, 85);
    lv_obj_set_y(ui_AceptButton3, 115);
    lv_obj_set_align(ui_AceptButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AceptButton3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_AceptButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AceptButton3, lv_color_hex(0x1F5F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AceptButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AceptButton3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AceptButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_AceptButton3);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "Aceptar");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumberButton = lv_button_create(ui_SocialScreen);
    lv_obj_set_width(ui_NumberButton, 75);
    lv_obj_set_height(ui_NumberButton, 40);
    lv_obj_set_x(ui_NumberButton, -85);
    lv_obj_set_y(ui_NumberButton, 115);
    lv_obj_set_align(ui_NumberButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NumberButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_NumberButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NumberButton, lv_color_hex(0x98C498), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NumberButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_NumberButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_NumberButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_NumberButton);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "1");
    lv_obj_set_style_text_font(ui_Label40, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeekDayRoller = lv_roller_create(ui_SocialScreen);
    lv_roller_set_options(ui_WeekDayRoller, "Actual\nLunes\nMartes\nMiércoles\nJueves\nViernes\nSábado\nDomingo",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_WeekDayRoller, 125);
    lv_obj_set_width(ui_WeekDayRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_WeekDayRoller, 0);
    lv_obj_set_y(ui_WeekDayRoller, -2);
    lv_obj_set_align(ui_WeekDayRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WeekDayRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_WeekDayRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeekDayRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeekDayRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WeekDayRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeekDayRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WeekDayRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WeekDayRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WeekDayRoller, lv_color_hex(0x39B639), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeekDayRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_TimeRoller = lv_roller_create(ui_SocialScreen);
    lv_roller_set_options(ui_TimeRoller,
                          "Hoy\nMañana\nAyer\nAhora\nDespués\nAntes\nEsta semana\nLa semana que viene\nEste mes\nTodo el día\nUn rato\nUn momento\nTarde\nTemprano\nA la noche\nA la mañana\nA la tarde",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_TimeRoller, 125);
    lv_obj_set_width(ui_TimeRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_TimeRoller, 0);
    lv_obj_set_y(ui_TimeRoller, -2);
    lv_obj_set_align(ui_TimeRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TimeRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_TimeRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TimeRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TimeRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TimeRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TimeRoller, lv_color_hex(0x39B639), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_HourRoller = lv_roller_create(ui_SocialScreen);
    lv_roller_set_options(ui_HourRoller,
                          "En punto\nY cuarto\nY media\nMenos cuarto\nDe mañana\nDe tarde\nDe noche\nMediodía\nMedianoche",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_HourRoller, 125);
    lv_obj_set_width(ui_HourRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_HourRoller, 0);
    lv_obj_set_y(ui_HourRoller, -2);
    lv_obj_set_align(ui_HourRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HourRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_HourRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HourRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HourRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HourRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HourRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HourRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_HourRoller, lv_color_hex(0x39B639), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_AskRoller = lv_roller_create(ui_SocialScreen);
    lv_roller_set_options(ui_AskRoller,
                          "¿Cómo estás?\n¿Qué estás haciendo?\n¿Qué pasó?\n¿Dónde estamos?\n¿Cómo te llamás?\n¿Querés algo?\n¿Qué querés hacer?\n¿Podés ayudarme?\n¿Dónde está el baño?\n¿Qué te pasa?\n¿Cuál es la contraseña?\n¿Podés esperarme?\n¿Me podés acompañar?\n¿Cómo llego a este lugar?\n¿Cuánto cuesta?\nPorque sí\nPorque no\nPorque lo necesito\nPorque necesito hacerlo\nPorque no quiero\nPorque quiero\nPorque puedo\nPorque no puedo\nNo sé por qué\nNo sé",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_AskRoller, 125);
    lv_obj_set_width(ui_AskRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_AskRoller, 0);
    lv_obj_set_y(ui_AskRoller, -2);
    lv_obj_set_align(ui_AskRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AskRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_AskRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AskRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AskRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AskRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AskRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AskRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AskRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_AskRoller, lv_color_hex(0x39B639), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AskRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_AnimoScreen = lv_obj_create(ui_WordYPhra);
    lv_obj_set_width(ui_AnimoScreen, 480);
    lv_obj_set_height(ui_AnimoScreen, 320);
    lv_obj_set_align(ui_AnimoScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AnimoScreen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_AnimoScreen, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AnimoScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AnimoScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AnimoScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AnimoScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AnimoRoller = lv_roller_create(ui_AnimoScreen);
    lv_roller_set_options(ui_AnimoRoller,
                          "¡Qué gusto!\nEstoy triste\nEstoy cansado\nTengo hambre\nTengo sed\n¡Qué frío que hace!\n¡Qué calor que hace!\nNo me siento bien\n¡Estoy bien!\nEstoy preocupado\n¡Estoy muy nervioso!\nTengo sueño\nNecesito descansar\nNecesito ayuda\nMe duele acá\nPosiciones...\nCuerpo...\nRutina diaria...\nColores...\nDeportes...\nLugares...",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_AnimoRoller, 125);
    lv_obj_set_width(ui_AnimoRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_AnimoRoller, 0);
    lv_obj_set_y(ui_AnimoRoller, -2);
    lv_obj_set_align(ui_AnimoRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_AnimoRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AnimoRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AnimoRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AnimoRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AnimoRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AnimoRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AnimoRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_AnimoRoller, lv_color_hex(0x2050FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AnimoRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_AceptarButton2 = lv_button_create(ui_AnimoScreen);
    lv_obj_set_width(ui_AceptarButton2, 125);
    lv_obj_set_height(ui_AceptarButton2, 40);
    lv_obj_set_x(ui_AceptarButton2, 146);
    lv_obj_set_y(ui_AceptarButton2, 115);
    lv_obj_set_align(ui_AceptarButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AceptarButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_AceptarButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AceptarButton2, lv_color_hex(0x2C3C75), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AceptarButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AceptarButton2, lv_color_hex(0x5668A9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AceptarButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_AceptarButton2);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "Aceptar");
    lv_obj_set_style_text_font(ui_Label30, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PositionRoller = lv_roller_create(ui_AnimoScreen);
    lv_roller_set_options(ui_PositionRoller,
                          "Arriba\nAbajo\nAdelante\nAtrás\nAdentro\nAfuera\nAl lado\nEnfrente\nSentado\nParado\nAcostado\nDe pie\nCerca\nLejos",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_PositionRoller, 125);
    lv_obj_set_width(ui_PositionRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_PositionRoller, 0);
    lv_obj_set_y(ui_PositionRoller, -2);
    lv_obj_set_align(ui_PositionRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PositionRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_PositionRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PositionRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PositionRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PositionRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PositionRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PositionRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PositionRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PositionRoller, lv_color_hex(0x2050FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PositionRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_BodyRoller = lv_roller_create(ui_AnimoScreen);
    lv_roller_set_options(ui_BodyRoller,
                          "Cabeza\nBrazo\nPierna\nMano\nPie\nOjo\nOído\nBoca\nNariz\nEspalda\nPanza\nRodilla\nDedo\nCuello\nHombro",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_BodyRoller, 125);
    lv_obj_set_width(ui_BodyRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_BodyRoller, 0);
    lv_obj_set_y(ui_BodyRoller, -2);
    lv_obj_set_align(ui_BodyRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BodyRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_BodyRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BodyRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BodyRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BodyRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BodyRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BodyRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BodyRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BodyRoller, lv_color_hex(0x2050FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BodyRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_RutineRoller = lv_roller_create(ui_AnimoScreen);
    lv_roller_set_options(ui_RutineRoller,
                          "Despertar\nBañarse\nVestirse\nDesayunar\nCepillarse los dientes\nIr a la escuela\nEstudiar\nJugar\nAlmorzar\nMerendar\nCenar\nBañarse de noche\nDormir",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_RutineRoller, 125);
    lv_obj_set_width(ui_RutineRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_RutineRoller, 0);
    lv_obj_set_y(ui_RutineRoller, -2);
    lv_obj_set_align(ui_RutineRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RutineRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_RutineRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RutineRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RutineRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RutineRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RutineRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RutineRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RutineRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RutineRoller, lv_color_hex(0x2050FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RutineRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ColorRoller = lv_roller_create(ui_AnimoScreen);
    lv_roller_set_options(ui_ColorRoller,
                          "Rojo\nAzul\nVerde\nAmarillo\nNaranja\nVioleta\nRosa\nMarrón\nNegro\nBlanco\nGris\nCeleste", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_ColorRoller, 125);
    lv_obj_set_width(ui_ColorRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ColorRoller, 0);
    lv_obj_set_y(ui_ColorRoller, -2);
    lv_obj_set_align(ui_ColorRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ColorRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_ColorRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ColorRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ColorRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ColorRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ColorRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ColorRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ColorRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ColorRoller, lv_color_hex(0x2050FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ColorRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_SportRoller = lv_roller_create(ui_AnimoScreen);
    lv_roller_set_options(ui_SportRoller,
                          "Fútbol\nBásquet\nVóley\nNatación\nAtletismo\nTenis\nCiclismo\nKarate\nBaile\nGimnasia", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_SportRoller, 125);
    lv_obj_set_width(ui_SportRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_SportRoller, 0);
    lv_obj_set_y(ui_SportRoller, -2);
    lv_obj_set_align(ui_SportRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SportRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_SportRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SportRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SportRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SportRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SportRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SportRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SportRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SportRoller, lv_color_hex(0x2050FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SportRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_PlaceRoller = lv_roller_create(ui_AnimoScreen);
    lv_roller_set_options(ui_PlaceRoller,
                          "Casa\nEscuela\nHospital\nParque\nTienda\nBaño\nCocina\nHabitación\nIglesia\nPlaza\nFarmacia\nSupermercado",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_PlaceRoller, 125);
    lv_obj_set_width(ui_PlaceRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_PlaceRoller, 0);
    lv_obj_set_y(ui_PlaceRoller, -2);
    lv_obj_set_align(ui_PlaceRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PlaceRoller, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_PlaceRoller, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlaceRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PlaceRoller, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PlaceRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlaceRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PlaceRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PlaceRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PlaceRoller, lv_color_hex(0x2050FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlaceRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_CancelButton2 = lv_button_create(ui_AnimoScreen);
    lv_obj_set_width(ui_CancelButton2, 125);
    lv_obj_set_height(ui_CancelButton2, 40);
    lv_obj_set_x(ui_CancelButton2, -85);
    lv_obj_set_y(ui_CancelButton2, 115);
    lv_obj_set_align(ui_CancelButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CancelButton2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CancelButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CancelButton2, lv_color_hex(0x6E7BA0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CancelButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CancelButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CancelButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_CancelButton2);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Cancelar");
    lv_obj_set_style_text_font(ui_Label31, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AceptButton2 = lv_button_create(ui_AnimoScreen);
    lv_obj_set_width(ui_AceptButton2, 125);
    lv_obj_set_height(ui_AceptButton2, 40);
    lv_obj_set_x(ui_AceptButton2, 85);
    lv_obj_set_y(ui_AceptButton2, 115);
    lv_obj_set_align(ui_AceptButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AceptButton2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_AceptButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AceptButton2, lv_color_hex(0x293C73), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AceptButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AceptButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AceptButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_AceptButton2);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "Aceptar");
    lv_obj_set_style_text_font(ui_Label32, &ui_font_Font28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_AnimoScreen);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -92);
    lv_obj_set_y(ui_Label35, -112);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "Animo");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0x2352FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &ui_font_DESIGNER36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_DailyButton, ui_event_DailyButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FoodButton, ui_event_FoodButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SocialButton, ui_event_SocialButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AnimoButton, ui_event_AnimoButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DailyScreen, ui_event_DailyScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FoodScreen, ui_event_FoodScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SocialScreen, ui_event_SocialScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AnimoScreen, ui_event_AnimoScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WordYPhra, ui_event_WordYPhra, LV_EVENT_ALL, NULL);

    // ------------------- PIAM Pro: eventos de voz/navegacion -------------------
    lv_obj_add_event_cb(ui_AceptarButton, ui_event_AceptarButton_daily, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_CancelButton, ui_event_CancelButton_daily, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_AceptButton, ui_event_AceptButton_daily, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_FemButton, ui_event_FemButton_daily, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_MascButton, ui_event_MascButton_daily, LV_EVENT_CLICKED, NULL);

    lv_obj_add_event_cb(ui_AceptarButton1, ui_event_AceptarButton_food, LV_EVENT_CLICKED, NULL);

    lv_obj_add_event_cb(ui_AceptarButton3, ui_event_AceptarButton_social, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_CancelButton3, ui_event_CancelButton_social, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_AceptButton3, ui_event_AceptButton_social, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_NumberButton, ui_event_NumberButton_social, LV_EVENT_CLICKED, NULL);

    lv_obj_add_event_cb(ui_AceptarButton2, ui_event_AceptarButton_animo, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_CancelButton2, ui_event_CancelButton_animo, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_AceptButton2, ui_event_AceptButton_animo, LV_EVENT_CLICKED, NULL);
    // -----------------------------------------------------------------------

}

void ui_WordYPhra_screen_destroy(void)
{
    if(ui_WordYPhra) lv_obj_del(ui_WordYPhra);

    // NULL screen variables
    ui_WordYPhra = NULL;
    ui_DailyCont = NULL;
    ui_DailyButton = NULL;
    ui_FoodCont = NULL;
    ui_FoodButton = NULL;
    ui_SocialCont = NULL;
    ui_SocialButton = NULL;
    ui_AnimoCont = NULL;
    ui_AnimoButton = NULL;
    ui_DailyScreen = NULL;
    ui_DailyRoller = NULL;
    ui_AceptarButton = NULL;
    ui_Label15 = NULL;
    ui_AdjRoller = NULL;
    ui_VerbRoller = NULL;
    ui_QuantRoller = NULL;
    ui_PeopleRoller = NULL;
    ui_CountryRoller = NULL;
    ui_StateRoller = NULL;
    ui_CancelButton = NULL;
    ui_Label17 = NULL;
    ui_AceptButton = NULL;
    ui_Label16 = NULL;
    ui_FemButton = NULL;
    ui_Label18 = NULL;
    ui_MascButton = NULL;
    ui_Label19 = NULL;
    ui_Label14 = NULL;
    ui_FoodScreen = NULL;
    ui_FoodRoller = NULL;
    ui_AceptarButton1 = NULL;
    ui_Label20 = NULL;
    ui_Label25 = NULL;
    ui_SocialScreen = NULL;
    ui_SocialRoller = NULL;
    ui_AceptarButton3 = NULL;
    ui_Label36 = NULL;
    ui_Label37 = NULL;
    ui_CancelButton3 = NULL;
    ui_Label38 = NULL;
    ui_AceptButton3 = NULL;
    ui_Label39 = NULL;
    ui_NumberButton = NULL;
    ui_Label40 = NULL;
    ui_WeekDayRoller = NULL;
    ui_TimeRoller = NULL;
    ui_HourRoller = NULL;
    ui_AskRoller = NULL;
    ui_AnimoScreen = NULL;
    ui_AnimoRoller = NULL;
    ui_AceptarButton2 = NULL;
    ui_Label30 = NULL;
    ui_PositionRoller = NULL;
    ui_BodyRoller = NULL;
    ui_RutineRoller = NULL;
    ui_ColorRoller = NULL;
    ui_SportRoller = NULL;
    ui_PlaceRoller = NULL;
    ui_CancelButton2 = NULL;
    ui_Label31 = NULL;
    ui_AceptButton2 = NULL;
    ui_Label32 = NULL;
    ui_Label35 = NULL;

}
