// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: PIAM_Pro

#ifndef UI_WORDYPHRA_H
#define UI_WORDYPHRA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WordYPhra
extern void ui_WordYPhra_screen_init(void);
extern void ui_WordYPhra_screen_destroy(void);
extern void ui_event_WordYPhra(lv_event_t * e);
extern lv_obj_t * ui_WordYPhra;
extern lv_obj_t * ui_DailyCont;
extern void ui_event_DailyButton(lv_event_t * e);
extern lv_obj_t * ui_DailyButton;
extern lv_obj_t * ui_FoodCont;
extern void ui_event_FoodButton(lv_event_t * e);
extern lv_obj_t * ui_FoodButton;
extern lv_obj_t * ui_SocialCont;
extern void ui_event_SocialButton(lv_event_t * e);
extern lv_obj_t * ui_SocialButton;
extern lv_obj_t * ui_AnimoCont;
extern void ui_event_AnimoButton(lv_event_t * e);
extern lv_obj_t * ui_AnimoButton;
extern void ui_event_DailyScreen(lv_event_t * e);
extern lv_obj_t * ui_DailyScreen;
extern lv_obj_t * ui_DailyRoller;
extern lv_obj_t * ui_AceptarButton;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_AdjRoller;
extern lv_obj_t * ui_VerbRoller;
extern lv_obj_t * ui_QuantRoller;
extern lv_obj_t * ui_PeopleRoller;
extern lv_obj_t * ui_CountryRoller;
extern lv_obj_t * ui_StateRoller;
extern lv_obj_t * ui_CancelButton;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_AceptButton;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_FemButton;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_MascButton;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label14;
extern void ui_event_FoodScreen(lv_event_t * e);
extern lv_obj_t * ui_FoodScreen;
extern lv_obj_t * ui_FoodRoller;
extern lv_obj_t * ui_AceptarButton1;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_CancelButton1;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_AceptButton1;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_CheeseRoller;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_PastaRoller;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_VeggieRoller;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_CandyRoller;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_DrinkRoller;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_FishRoller;
extern lv_obj_t * ui_Label29;
extern void ui_event_SocialScreen(lv_event_t * e);
extern lv_obj_t * ui_SocialScreen;
extern lv_obj_t * ui_SocialRoller;
extern lv_obj_t * ui_AceptarButton3;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_CancelButton3;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_AceptButton3;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_NumberButton;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_WeekDayRoller;
extern lv_obj_t * ui_MonthRoller;
extern lv_obj_t * ui_TimeRoller;
extern lv_obj_t * ui_HourRoller;
extern lv_obj_t * ui_WeatherRoller;
extern lv_obj_t * ui_AskRoller;
extern void ui_event_AnimoScreen(lv_event_t * e);
extern lv_obj_t * ui_AnimoScreen;
extern lv_obj_t * ui_AnimoRoller;
extern lv_obj_t * ui_AceptarButton2;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_PositionRoller;
extern lv_obj_t * ui_BodyRoller;
extern lv_obj_t * ui_EmotionRoller;
extern lv_obj_t * ui_RutineRoller;
extern lv_obj_t * ui_ColorRoller;
extern lv_obj_t * ui_SportRoller;
extern lv_obj_t * ui_PlaceRoller;
extern lv_obj_t * ui_CancelButton2;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_AceptButton2;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label35;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

