// This file was generated by SquareLine Vision Exporter
// Project name: PIAM Pro

#include "../GUI.h"

// Animation timeline variables, one for each animation triggered by an event
lv_anim_timeline_t *GUI_Timeline__BarValue;
lv_anim_timeline_t *GUI_Timeline__MenuAnim;

static void GUI_createTimelinePhase(lv_anim_timeline_t *timeline, uint32_t start_time, lv_anim_t *animation,
                                    lv_obj_t *object, lv_anim_custom_exec_cb_t animator, int32_t startvalue,
                                    int32_t endvalue, uint32_t duration, lv_anim_path_cb_t animpath, bool early_apply) {
    lv_anim_init(animation);
    lv_anim_set_var(animation, object);
    lv_anim_set_early_apply(animation, early_apply);
    lv_anim_set_custom_exec_cb(animation, animator);
    lv_anim_set_values(animation, startvalue, endvalue);
    lv_anim_set_duration(animation, duration);
    lv_anim_set_path_cb(animation, animpath);
    lv_anim_timeline_add(timeline, start_time, animation);
}

static void GUI_animatorCallback__Set_X(lv_anim_t *var, int32_t v) {
    lv_obj_set_x(var->var, v);
}

static void GUI_animatorCallback__Set_Y(lv_anim_t *var, int32_t v) {
    lv_obj_set_y(var->var, v);
}

static void GUI_animatorCallback__Set_WIDTH(lv_anim_t *var, int32_t v) {
    lv_obj_set_width(var->var, v);
}

static void GUI_animatorCallback__Set_HEIGHT(lv_anim_t *var, int32_t v) {
    lv_obj_set_height(var->var, v);
}

static void GUI_animatorCallback__Set_OPACITY(lv_anim_t *var, int32_t v) {
    lv_obj_set_style_opa(var->var, v * 255 / 100, 0);
}

void GUI_initAnimations() {
    GUI_Timeline__BarValue = lv_anim_timeline_create();
    static lv_anim_t GUI_anim_0;
    GUI_createTimelinePhase(GUI_Timeline__BarValue, 1233, &GUI_anim_0, GUI_Bar__HOME__Bar,
                            GUI_animatorCallback__Set_WIDTH, 0, 380, 4533, lv_anim_path_linear, true);

    GUI_Timeline__MenuAnim = lv_anim_timeline_create();
    static lv_anim_t GUI_anim_1;
    GUI_createTimelinePhase(GUI_Timeline__MenuAnim, 0, &GUI_anim_1, GUI_Button__MENU__SetButton,
                            GUI_animatorCallback__Set_X, -1, 0, 267, lv_anim_path_linear, true);
    static lv_anim_t GUI_anim_2;
    GUI_createTimelinePhase(GUI_Timeline__MenuAnim, 0, &GUI_anim_2, GUI_Button__MENU__SetButton,
                            GUI_animatorCallback__Set_Y, 122, 10, 267, lv_anim_path_linear, true);
    static lv_anim_t GUI_anim_3;
    GUI_createTimelinePhase(GUI_Timeline__MenuAnim, 0, &GUI_anim_3, GUI_Button__MENU__SOSButton,
                            GUI_animatorCallback__Set_X, 204, 75, 267, lv_anim_path_linear, true);
    static lv_anim_t GUI_anim_4;
    GUI_createTimelinePhase(GUI_Timeline__MenuAnim, 0, &GUI_anim_4, GUI_Button__MENU__SOSButton,
                            GUI_animatorCallback__Set_Y, 1, -25, 267, lv_anim_path_linear, true);
    static lv_anim_t GUI_anim_5;
    GUI_createTimelinePhase(GUI_Timeline__MenuAnim, 0, &GUI_anim_5, GUI_Button__MENU__CalcButton,
                            GUI_animatorCallback__Set_X, -202, -75, 267, lv_anim_path_linear, true);
    static lv_anim_t GUI_anim_6;
    GUI_createTimelinePhase(GUI_Timeline__MenuAnim, 0, &GUI_anim_6, GUI_Button__MENU__CalcButton,
                            GUI_animatorCallback__Set_Y, 0, -25, 267, lv_anim_path_linear, true);
    static lv_anim_t GUI_anim_7;
    GUI_createTimelinePhase(GUI_Timeline__MenuAnim, 0, &GUI_anim_7, GUI_Button__MENU__PaintButton,
                            GUI_animatorCallback__Set_X, 202, 125, 267, lv_anim_path_linear, true);
    static lv_anim_t GUI_anim_8;
    GUI_createTimelinePhase(GUI_Timeline__MenuAnim, 0, &GUI_anim_8, GUI_Button__MENU__PaintButton,
                            GUI_animatorCallback__Set_Y, -120, -25, 267, lv_anim_path_linear, true);
    static lv_anim_t GUI_anim_9;
    GUI_createTimelinePhase(GUI_Timeline__MenuAnim, 0, &GUI_anim_9, GUI_Button__MENU__ChronosButton,
                            GUI_animatorCallback__Set_X, -203, -125, 267, lv_anim_path_linear, true);
    static lv_anim_t GUI_anim_10;
    GUI_createTimelinePhase(GUI_Timeline__MenuAnim, 0, &GUI_anim_10, GUI_Button__MENU__ChronosButton,
                            GUI_animatorCallback__Set_Y, -125, -25, 267, lv_anim_path_linear, true);
    static lv_anim_t GUI_anim_11;
    GUI_createTimelinePhase(GUI_Timeline__MenuAnim, 0, &GUI_anim_11, GUI_Button__MENU__OpenMenu,
                            GUI_animatorCallback__Set_WIDTH, 100, 0, 400, lv_anim_path_linear, true);
    static lv_anim_t GUI_anim_12;
    GUI_createTimelinePhase(GUI_Timeline__MenuAnim, 0, &GUI_anim_12, GUI_Button__MENU__OpenMenu,
                            GUI_animatorCallback__Set_HEIGHT, 100, 0, 400, lv_anim_path_linear, true);
    static lv_anim_t GUI_anim_13;
    GUI_createTimelinePhase(GUI_Timeline__MenuAnim, 0, &GUI_anim_13, GUI_Button__MENU__PSButton,
                            GUI_animatorCallback__Set_WIDTH, 0, 95, 400, lv_anim_path_linear, true);
    static lv_anim_t GUI_anim_14;
    GUI_createTimelinePhase(GUI_Timeline__MenuAnim, 0, &GUI_anim_14, GUI_Button__MENU__PSButton,
                            GUI_animatorCallback__Set_HEIGHT, 0, 95, 400, lv_anim_path_linear, true);
}
