// This file was generated by SquareLine Vision Exporter
// Project name: PIAM Pro

#include "../GUI.h"

#ifdef GUI_EXTERNAL_CUSTOM_CALLBACK_FUNCTION_FILE
#include GUI_EXTERNAL_CUSTOM_CALLBACK_FUNCTION_FILE
#endif

void GUI_event__Screen__HOME__Screen_Loaded(lv_event_t *event) {
    if (GUI_Timeline__BarValue == NULL)
        return;
    lv_anim_timeline_set_progress(GUI_Timeline__BarValue, 0); // Reset animation to start
    lv_anim_timeline_start(GUI_Timeline__BarValue);           // Play_Animation
    _ui_screen_change(&GUI_Screen__HOUR, LV_SCR_LOAD_ANIM_NONE, 0, 6500, &GUI_initScreen__HOUR); // Change_Screen
}

void GUI_event__Container__HOUR__Container__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__MENU, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &GUI_initScreen__MENU); // Change_Screen
}

void GUI_event__Button__MENU__PSButton__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__PIAMSYS, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &GUI_initScreen__PIAMSYS); // Change_Screen
}

void GUI_event__Button__MENU__SetButton__Clicked(lv_event_t *event) {
    // WARN: Change-screen references unknown screen ID "null"
}

void GUI_event__Button__MENU__OpenMenu__Clicked(lv_event_t *event) {
    if (GUI_Timeline__MenuAnim == NULL)
        return;
    lv_anim_timeline_set_progress(GUI_Timeline__MenuAnim, 0);               // Reset animation to start
    lv_anim_timeline_start(GUI_Timeline__MenuAnim);                         // Play_Animation
    lv_obj_clear_flag(GUI_Button__MENU__PSButton, LV_OBJ_FLAG_HIDDEN);      // Modify_Flag
    lv_obj_clear_flag(GUI_Button__MENU__SetButton, LV_OBJ_FLAG_HIDDEN);     // Modify_Flag
    lv_obj_clear_flag(GUI_Button__MENU__SOSButton, LV_OBJ_FLAG_HIDDEN);     // Modify_Flag
    lv_obj_clear_flag(GUI_Button__MENU__CalcButton, LV_OBJ_FLAG_HIDDEN);    // Modify_Flag
    lv_obj_clear_flag(GUI_Button__MENU__PaintButton, LV_OBJ_FLAG_HIDDEN);   // Modify_Flag
    lv_obj_clear_flag(GUI_Button__MENU__ChronosButton, LV_OBJ_FLAG_HIDDEN); // Modify_Flag
    lv_obj_clear_flag(GUI_Button__MENU__Button, LV_OBJ_FLAG_HIDDEN);        // Modify_Flag
}

void GUI_event__Button__MENU__Button__Clicked(lv_event_t *event) {
    lv_obj_add_flag(GUI_Button__MENU__SetButton, LV_OBJ_FLAG_HIDDEN);     // Modify_Flag
    lv_obj_add_flag(GUI_Button__MENU__PSButton, LV_OBJ_FLAG_HIDDEN);      // Modify_Flag
    lv_obj_add_flag(GUI_Button__MENU__SOSButton, LV_OBJ_FLAG_HIDDEN);     // Modify_Flag
    lv_obj_add_flag(GUI_Button__MENU__CalcButton, LV_OBJ_FLAG_HIDDEN);    // Modify_Flag
    lv_obj_add_flag(GUI_Button__MENU__PaintButton, LV_OBJ_FLAG_HIDDEN);   // Modify_Flag
    lv_obj_add_flag(GUI_Button__MENU__ChronosButton, LV_OBJ_FLAG_HIDDEN); // Modify_Flag
    lv_obj_add_flag(GUI_Button__MENU__Button, LV_OBJ_FLAG_HIDDEN);        // Modify_Flag
    lv_obj_set_width(GUI_Button__MENU__OpenMenu, 100);                    // Basic_Properties
    lv_obj_set_height(GUI_Button__MENU__OpenMenu, 100);                   // Basic_Properties
}

void GUI_event__Screen__PIAMSYS__Gesture_Top(lv_event_t *event) {
    if (lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        _ui_screen_change(&GUI_Screen__MENU, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &GUI_initScreen__MENU); // Change_Screen
    }
}
