// This file was generated by SquareLine Vision Exporter
// Project name: PIAM Pro

#ifndef _GUI_CORE_H
#define _GUI_CORE_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// Animation timeline declarations, one for each event
extern lv_anim_timeline_t *GUI_Timeline__BarValue;
extern lv_anim_timeline_t *GUI_Timeline__MenuAnim;

// Screen-specific function declarations
void GUI_initScreen__HOME();
void GUI_initScreenTexts__HOME();
void GUI_initScreenStyles__HOME();

void GUI_initScreen__HOUR();
void GUI_initScreenTexts__HOUR();
void GUI_initScreenStyles__HOUR();

void GUI_initScreen__MENU();
void GUI_initScreenTexts__MENU();
void GUI_initScreenStyles__MENU();

void GUI_initScreen__PIAMSYS();
void GUI_initScreenTexts__PIAMSYS();
void GUI_initScreenStyles__PIAMSYS();

void GUI_initScreen__SOS();
void GUI_initScreenTexts__SOS();
void GUI_initScreenStyles__SOS();

void GUI_initScreen__CALCULATOR();
void GUI_initScreenTexts__CALCULATOR();
void GUI_initScreenStyles__CALCULATOR();

void GUI_initScreen__SETTINGS();
void GUI_initScreenTexts__SETTINGS();
void GUI_initScreenStyles__SETTINGS();

void GUI_load();

void GUI_init();

void GUI_refresh();

void GUI_initHAL();
void HAL_init();

void GUI_initFramework();

void GUI_loadContent();

void GUI_initContent();

void GUI_initTheme();

void GUI_initScreens();

void GUI_loadFirstScreen();

void GUI_initScreenContents();

void GUI_initScreenTexts();

void GUI_initScreenStyles();

void GUI_initAnimations();

void GUI_event__Screen__HOME__Screen_Loaded(lv_event_t *event);
void GUI_event__Container__HOUR__Container__Clicked(lv_event_t *event);
void GUI_event__Button__MENU__PSButton__Clicked(lv_event_t *event);
void GUI_event__Button__MENU__SetButton__Clicked(lv_event_t *event);
void GUI_event__Button__MENU__OpenMenu__Clicked(lv_event_t *event);
void GUI_event__Button__MENU__Button__Clicked(lv_event_t *event);
void GUI_event__Screen__PIAMSYS__Gesture_Top(lv_event_t *event);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
