// This file was generated by SquareLine Vision Exporter
// Project name: PIAM Pro

#include "../GUI.h"

void GUI_load() {
    GUI_initFramework();
    GUI_initHAL();
    GUI_loadContent();
}

void GUI_init() {
    GUI_loadContent();
}

void GUI_refresh() {
    lv_timer_handler();
    //...
}

void GUI_initHAL() {
    HAL_init();
}

void GUI_initFramework() {
    lv_init();
}

void GUI_loadContent() {
    GUI_initContent();
    GUI_loadFirstScreen();
}

void GUI_initContent() {
    GUI_initTheme();
    GUI_initScreens();
    GUI_initAnimations();
}

void GUI_initTheme() {
    lv_display_t *Display = lv_display_get_default();
    lv_theme_t *Theme = lv_theme_default_init(Display, lv_palette_main(LV_PALETTE_BLUE),
                                              lv_palette_main(LV_PALETTE_RED), false, lv_font_get_default());
    lv_display_set_theme(Display, Theme);
}

void GUI_initScreens() {
    GUI_initScreenContents();
}

void GUI_loadFirstScreen() {
    lv_screen_load(GUI_Screen__HOME);
}

void GUI_initScreenContents() {
    GUI_initScreen__HOME();
    GUI_initScreen__HOUR();
    GUI_initScreen__MENU();
    GUI_initScreen__PIAMSYS();
    GUI_initScreen__SOS();
    GUI_initScreen__CALCULATOR();
    GUI_initScreen__SETTINGS();
}

void GUI_initScreenTexts() {
    GUI_initScreenTexts__HOME();
    GUI_initScreenTexts__HOUR();
    GUI_initScreenTexts__MENU();
    GUI_initScreenTexts__PIAMSYS();
    GUI_initScreenTexts__SOS();
    GUI_initScreenTexts__CALCULATOR();
    GUI_initScreenTexts__SETTINGS();
}

void GUI_initScreenStyles() {
    GUI_initScreenStyles__HOME();
    GUI_initScreenStyles__HOUR();
    GUI_initScreenStyles__MENU();
    GUI_initScreenStyles__PIAMSYS();
    GUI_initScreenStyles__SOS();
    GUI_initScreenStyles__CALCULATOR();
    GUI_initScreenStyles__SETTINGS();
}
