// This file was generated by SquareLine Vision Exporter
// Project name: PIAM Pro

#ifndef _GUI_VARIABLES_H
#define _GUI_VARIABLES_H

#include "gui_core.h"

#ifdef __cplusplus
extern "C" {
#endif

extern lv_obj_t *GUI_Screen__HOME;
extern lv_obj_t *GUI_Image__HOME__Image;
extern lv_obj_t *GUI_Bar__HOME__Bar;

extern lv_obj_t *GUI_Screen__HOUR;
extern lv_obj_t *GUI_Container__HOUR__Container;
extern lv_obj_t *GUI_Label__HOUR__Label;
extern lv_obj_t *GUI_Label__HOUR__Label_1;

extern lv_obj_t *GUI_Screen__MENU;
extern lv_obj_t *GUI_Button__MENU__PSButton;
extern lv_obj_t *GUI_Button__MENU__SetButton;
extern lv_obj_t *GUI_Button__MENU__SOSButton;
extern lv_obj_t *GUI_Button__MENU__CalcButton;
extern lv_obj_t *GUI_Button__MENU__PaintButton;
extern lv_obj_t *GUI_Button__MENU__ChronosButton;
extern lv_obj_t *GUI_Button__MENU__OpenMenu;
extern lv_obj_t *GUI_Button__MENU__Button;

extern lv_obj_t *GUI_Screen__PIAMSYS;
extern lv_obj_t *GUI_Button__PIAMSYS__Button_1;
extern lv_obj_t *GUI_Button__PIAMSYS__Button_2;

extern lv_obj_t *GUI_Screen__SOS;

extern lv_obj_t *GUI_Screen__CALCULATOR;

extern lv_obj_t *GUI_Screen__SETTINGS;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
