// This file was generated by SquareLine Vision Exporter
// Project name: PIAM Pro

#include "../GUI.h"

lv_obj_t *GUI_Screen__HOME;
lv_obj_t *GUI_Image__HOME__Image;
lv_obj_t *GUI_Bar__HOME__Bar;

lv_obj_t *GUI_Screen__HOUR;
lv_obj_t *GUI_Container__HOUR__Container;
lv_obj_t *GUI_Label__HOUR__Label;
lv_obj_t *GUI_Label__HOUR__Label_1;

lv_obj_t *GUI_Screen__MENU;
lv_obj_t *GUI_Button__MENU__PSButton;
lv_obj_t *GUI_Button__MENU__SetButton;
lv_obj_t *GUI_Button__MENU__SOSButton;
lv_obj_t *GUI_Button__MENU__CalcButton;
lv_obj_t *GUI_Button__MENU__PaintButton;
lv_obj_t *GUI_Button__MENU__ChronosButton;
lv_obj_t *GUI_Button__MENU__OpenMenu;
lv_obj_t *GUI_Button__MENU__Button;

lv_obj_t *GUI_Screen__PIAMSYS;
lv_obj_t *GUI_Button__PIAMSYS__Button_1;
lv_obj_t *GUI_Button__PIAMSYS__Button_2;

lv_obj_t *GUI_Screen__SOS;

lv_obj_t *GUI_Screen__CALCULATOR;

lv_obj_t *GUI_Screen__SETTINGS;
