// This file was generated by SquareLine Vision Exporter
// Project name: PIAM Pro

#include "../GUI.h"

void GUI_initScreen__CALCULATOR() {
    GUI_Screen__CALCULATOR = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__CALCULATOR, LV_OBJ_FLAG_SCROLLABLE);

    GUI_initScreenStyles__CALCULATOR();
    GUI_initScreenTexts__CALCULATOR();
}

void GUI_initScreenTexts__CALCULATOR() {
}

void GUI_initScreenStyles__CALCULATOR() {
    static lv_style_t GUI_Style__Screen__CALCULATOR__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Screen__CALCULATOR__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Screen__CALCULATOR__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Screen__CALCULATOR__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Screen__CALCULATOR__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Screen__CALCULATOR, &GUI_Style__Screen__CALCULATOR__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);
}
