// This file was generated by SquareLine Vision Exporter
// Project name: PIAM Pro

#include "../GUI.h"

void GUI_initScreen__HOME() {
    GUI_Screen__HOME = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__HOME, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(GUI_Screen__HOME, GUI_event__Screen__HOME__Screen_Loaded, LV_EVENT_SCREEN_LOADED, NULL);
    GUI_Image__HOME__Image = lv_image_create(GUI_Screen__HOME);
    lv_obj_add_flag(GUI_Image__HOME__Image, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__HOME__Image, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__HOME__Image, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__HOME__Image, 52, 64);
    lv_obj_set_size(GUI_Image__HOME__Image, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Bar__HOME__Bar = lv_bar_create(GUI_Screen__HOME);
    lv_bar_set_value(GUI_Bar__HOME__Bar, 100, LV_ANIM_OFF);
    lv_obj_set_align(GUI_Bar__HOME__Bar, LV_ALIGN_LEFT_MID);
    lv_obj_set_pos(GUI_Bar__HOME__Bar, 56, 95);
    lv_obj_set_size(GUI_Bar__HOME__Bar, 0, 15);

    GUI_initScreenStyles__HOME();
    GUI_initScreenTexts__HOME();
}

void GUI_initScreenTexts__HOME() {
}

void GUI_initScreenStyles__HOME() {
    static lv_style_t GUI_Style__Screen__HOME__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Screen__HOME__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Screen__HOME__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Screen__HOME__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Screen__HOME__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Screen__HOME, &GUI_Style__Screen__HOME__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__HOME__Image, &upload_piam_home_png);

    static lv_style_t GUI_Style__Image__HOME__Image__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Image__HOME__Image__MAIN_DEFAULT);
    lv_style_set_min_width(&GUI_Style__Image__HOME__Image__MAIN_DEFAULT, 0);
    lv_style_set_max_width(&GUI_Style__Image__HOME__Image__MAIN_DEFAULT, 8000);
    lv_style_set_min_height(&GUI_Style__Image__HOME__Image__MAIN_DEFAULT, 0);
    lv_style_set_max_height(&GUI_Style__Image__HOME__Image__MAIN_DEFAULT, 8000);
    lv_style_set_transform_scale_x(&GUI_Style__Image__HOME__Image__MAIN_DEFAULT, 100);
    lv_style_set_transform_scale_y(&GUI_Style__Image__HOME__Image__MAIN_DEFAULT, 100);
    lv_style_set_transform_rotation(&GUI_Style__Image__HOME__Image__MAIN_DEFAULT, 0);
    lv_style_set_transform_pivot_x(&GUI_Style__Image__HOME__Image__MAIN_DEFAULT, 0);
    lv_style_set_transform_pivot_y(&GUI_Style__Image__HOME__Image__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Image__HOME__Image, &GUI_Style__Image__HOME__Image__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Bar__HOME__Bar__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Bar__HOME__Bar__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Bar__HOME__Bar__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Bar__HOME__Bar__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Bar__HOME__Bar__MAIN_DEFAULT, 8000);
    lv_obj_add_style(GUI_Bar__HOME__Bar, &GUI_Style__Bar__HOME__Bar__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);
    static lv_style_t GUI_Style__Bar__HOME__Bar__INDICATOR_DEFAULT;
    lv_style_init(&GUI_Style__Bar__HOME__Bar__INDICATOR_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Bar__HOME__Bar__INDICATOR_DEFAULT, lv_color_make(91, 211, 219));
    lv_style_set_bg_opa(&GUI_Style__Bar__HOME__Bar__INDICATOR_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Bar__HOME__Bar__INDICATOR_DEFAULT, 32767);
    lv_obj_add_style(GUI_Bar__HOME__Bar, &GUI_Style__Bar__HOME__Bar__INDICATOR_DEFAULT,
                     LV_PART_INDICATOR | LV_STATE_DEFAULT);
}