// This file was generated by SquareLine Vision Exporter
// Project name: PIAM Pro

#include "../GUI.h"

void GUI_initScreen__HOUR() {
    GUI_Screen__HOUR = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__HOUR, LV_OBJ_FLAG_SCROLLABLE);
    GUI_Container__HOUR__Container = lv_obj_create(GUI_Screen__HOUR);
    lv_obj_remove_style_all(GUI_Container__HOUR__Container);
    lv_obj_remove_flag(GUI_Container__HOUR__Container, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__HOUR__Container, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Container__HOUR__Container, 102, 238);
    lv_obj_add_event_cb(GUI_Container__HOUR__Container, GUI_event__Container__HOUR__Container__Clicked,
                        LV_EVENT_CLICKED, NULL);

    GUI_Label__HOUR__Label = lv_label_create(GUI_Container__HOUR__Container);
    lv_label_set_long_mode(GUI_Label__HOUR__Label, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__HOUR__Label, LV_ALIGN_TOP_MID);
    lv_obj_set_size(GUI_Label__HOUR__Label, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__HOUR__Label_1 = lv_label_create(GUI_Container__HOUR__Container);
    lv_label_set_long_mode(GUI_Label__HOUR__Label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__HOUR__Label_1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_size(GUI_Label__HOUR__Label_1, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_initScreenStyles__HOUR();
    GUI_initScreenTexts__HOUR();
}

void GUI_initScreenTexts__HOUR() {
    lv_label_set_text_static(GUI_Label__HOUR__Label, "00");
    lv_label_set_text_static(GUI_Label__HOUR__Label_1, "00");
}

void GUI_initScreenStyles__HOUR() {
    static lv_style_t GUI_Style__Screen__HOUR__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Screen__HOUR__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Screen__HOUR__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Screen__HOUR__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Screen__HOUR__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Screen__HOUR, &GUI_Style__Screen__HOUR__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__HOUR__Label__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__HOUR__Label__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__HOUR__Label__MAIN_DEFAULT, &Bebas120);
    lv_style_set_text_color(&GUI_Style__Label__HOUR__Label__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Label__HOUR__Label__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__HOUR__Label__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__HOUR__Label__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__HOUR__Label__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__HOUR__Label, &GUI_Style__Label__HOUR__Label__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__HOUR__Label_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__HOUR__Label_1__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__HOUR__Label_1__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__HOUR__Label_1__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__HOUR__Label_1__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Label__HOUR__Label_1__MAIN_DEFAULT, lv_color_make(86, 206, 220));
    lv_style_set_text_opa(&GUI_Style__Label__HOUR__Label_1__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__HOUR__Label_1__MAIN_DEFAULT, &Bebas120);
    lv_obj_add_style(GUI_Label__HOUR__Label_1, &GUI_Style__Label__HOUR__Label_1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);
}
