// This file was generated by SquareLine Vision Exporter
// Project name: PIAM Pro

#include "../GUI.h"

void GUI_initScreen__MENU() {
    GUI_Screen__MENU = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__MENU, LV_OBJ_FLAG_SCROLLABLE);
    GUI_Button__MENU__PSButton = lv_button_create(GUI_Screen__MENU);
    lv_obj_set_align(GUI_Button__MENU__PSButton, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Button__MENU__PSButton, 95, 95);
    lv_obj_add_event_cb(GUI_Button__MENU__PSButton, GUI_event__Button__MENU__PSButton__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Button__MENU__SetButton = lv_button_create(GUI_Screen__MENU);
    lv_obj_set_align(GUI_Button__MENU__SetButton, LV_ALIGN_TOP_MID);
    lv_obj_set_pos(GUI_Button__MENU__SetButton, -1, 122);
    lv_obj_set_size(GUI_Button__MENU__SetButton, 75, 75);
    lv_obj_add_event_cb(GUI_Button__MENU__SetButton, GUI_event__Button__MENU__SetButton__Clicked, LV_EVENT_CLICKED,
                        NULL);

    GUI_Button__MENU__SOSButton = lv_button_create(GUI_Screen__MENU);
    lv_obj_set_align(GUI_Button__MENU__SOSButton, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(GUI_Button__MENU__SOSButton, 203);
    lv_obj_set_size(GUI_Button__MENU__SOSButton, 75, 75);

    GUI_Button__MENU__CalcButton = lv_button_create(GUI_Screen__MENU);
    lv_obj_set_align(GUI_Button__MENU__CalcButton, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(GUI_Button__MENU__CalcButton, -201);
    lv_obj_set_size(GUI_Button__MENU__CalcButton, 75, 75);

    GUI_Button__MENU__PaintButton = lv_button_create(GUI_Screen__MENU);
    lv_obj_set_align(GUI_Button__MENU__PaintButton, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_pos(GUI_Button__MENU__PaintButton, 202, -125);
    lv_obj_set_size(GUI_Button__MENU__PaintButton, 75, 75);

    GUI_Button__MENU__ChronosButton = lv_button_create(GUI_Screen__MENU);
    lv_obj_set_align(GUI_Button__MENU__ChronosButton, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_pos(GUI_Button__MENU__ChronosButton, -203, -122);
    lv_obj_set_size(GUI_Button__MENU__ChronosButton, 75, 75);

    GUI_Button__MENU__OpenMenu = lv_button_create(GUI_Screen__MENU);
    lv_obj_set_align(GUI_Button__MENU__OpenMenu, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Button__MENU__OpenMenu, 100, 100);
    lv_obj_add_event_cb(GUI_Button__MENU__OpenMenu, GUI_event__Button__MENU__OpenMenu__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Button__MENU__Button = lv_button_create(GUI_Screen__MENU);
    lv_obj_add_flag(GUI_Button__MENU__Button, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_pos(GUI_Button__MENU__Button, 15, 15);
    lv_obj_set_size(GUI_Button__MENU__Button, 40, 40);
    lv_obj_add_event_cb(GUI_Button__MENU__Button, GUI_event__Button__MENU__Button__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_initScreenStyles__MENU();
    GUI_initScreenTexts__MENU();
}

void GUI_initScreenTexts__MENU() {
}

void GUI_initScreenStyles__MENU() {
    static lv_style_t GUI_Style__Screen__MENU__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Screen__MENU__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Screen__MENU__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Screen__MENU__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Screen__MENU__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Screen__MENU__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Screen__MENU__MAIN_DEFAULT, 255);
    lv_style_set_shadow_offset_x(&GUI_Style__Screen__MENU__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Screen__MENU__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Screen__MENU__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Screen__MENU__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Screen__MENU, &GUI_Style__Screen__MENU__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__MENU__PSButton__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__MENU__PSButton__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__MENU__PSButton__MAIN_DEFAULT, lv_color_make(33, 210, 242));
    lv_style_set_bg_opa(&GUI_Style__Button__MENU__PSButton__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__MENU__PSButton__MAIN_DEFAULT, 90);
    lv_style_set_shadow_color(&GUI_Style__Button__MENU__PSButton__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__MENU__PSButton__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__MENU__PSButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__MENU__PSButton__MAIN_DEFAULT, 2);
    lv_style_set_shadow_width(&GUI_Style__Button__MENU__PSButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__MENU__PSButton__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__MENU__PSButton, &GUI_Style__Button__MENU__PSButton__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__MENU__SetButton__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__MENU__SetButton__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__MENU__SetButton__MAIN_DEFAULT, lv_color_make(0, 97, 255));
    lv_style_set_bg_opa(&GUI_Style__Button__MENU__SetButton__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__MENU__SetButton__MAIN_DEFAULT, 90);
    lv_style_set_shadow_color(&GUI_Style__Button__MENU__SetButton__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__MENU__SetButton__MAIN_DEFAULT, 128);
    lv_style_set_shadow_width(&GUI_Style__Button__MENU__SetButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__MENU__SetButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__MENU__SetButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__MENU__SetButton__MAIN_DEFAULT, 2);
    lv_obj_add_style(GUI_Button__MENU__SetButton, &GUI_Style__Button__MENU__SetButton__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__MENU__SOSButton__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__MENU__SOSButton__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__MENU__SOSButton__MAIN_DEFAULT, lv_color_make(135, 0, 255));
    lv_style_set_bg_opa(&GUI_Style__Button__MENU__SOSButton__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__MENU__SOSButton__MAIN_DEFAULT, 90);
    lv_style_set_shadow_color(&GUI_Style__Button__MENU__SOSButton__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__MENU__SOSButton__MAIN_DEFAULT, 128);
    lv_style_set_shadow_width(&GUI_Style__Button__MENU__SOSButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__MENU__SOSButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__MENU__SOSButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__MENU__SOSButton__MAIN_DEFAULT, 2);
    lv_obj_add_style(GUI_Button__MENU__SOSButton, &GUI_Style__Button__MENU__SOSButton__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__MENU__CalcButton__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__MENU__CalcButton__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__MENU__CalcButton__MAIN_DEFAULT, lv_color_make(251, 140, 149));
    lv_style_set_bg_opa(&GUI_Style__Button__MENU__CalcButton__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__MENU__CalcButton__MAIN_DEFAULT, 90);
    lv_style_set_shadow_color(&GUI_Style__Button__MENU__CalcButton__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__MENU__CalcButton__MAIN_DEFAULT, 128);
    lv_style_set_shadow_width(&GUI_Style__Button__MENU__CalcButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__MENU__CalcButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__MENU__CalcButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__MENU__CalcButton__MAIN_DEFAULT, 2);
    lv_obj_add_style(GUI_Button__MENU__CalcButton, &GUI_Style__Button__MENU__CalcButton__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__MENU__PaintButton__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__MENU__PaintButton__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__MENU__PaintButton__MAIN_DEFAULT, lv_color_make(250, 111, 183));
    lv_style_set_bg_opa(&GUI_Style__Button__MENU__PaintButton__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__MENU__PaintButton__MAIN_DEFAULT, 90);
    lv_style_set_shadow_color(&GUI_Style__Button__MENU__PaintButton__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__MENU__PaintButton__MAIN_DEFAULT, 128);
    lv_style_set_shadow_width(&GUI_Style__Button__MENU__PaintButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__MENU__PaintButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__MENU__PaintButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__MENU__PaintButton__MAIN_DEFAULT, 2);
    lv_obj_add_style(GUI_Button__MENU__PaintButton, &GUI_Style__Button__MENU__PaintButton__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__MENU__ChronosButton__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__MENU__ChronosButton__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__MENU__ChronosButton__MAIN_DEFAULT, lv_color_make(33, 242, 179));
    lv_style_set_bg_opa(&GUI_Style__Button__MENU__ChronosButton__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__MENU__ChronosButton__MAIN_DEFAULT, 90);
    lv_style_set_shadow_color(&GUI_Style__Button__MENU__ChronosButton__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__MENU__ChronosButton__MAIN_DEFAULT, 128);
    lv_style_set_shadow_width(&GUI_Style__Button__MENU__ChronosButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__MENU__ChronosButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__MENU__ChronosButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__MENU__ChronosButton__MAIN_DEFAULT, 2);
    lv_obj_add_style(GUI_Button__MENU__ChronosButton, &GUI_Style__Button__MENU__ChronosButton__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__MENU__OpenMenu__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__MENU__OpenMenu__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__MENU__OpenMenu__MAIN_DEFAULT, lv_color_make(165, 165, 165));
    lv_style_set_bg_opa(&GUI_Style__Button__MENU__OpenMenu__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__MENU__OpenMenu__MAIN_DEFAULT, 90);
    lv_style_set_shadow_color(&GUI_Style__Button__MENU__OpenMenu__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__MENU__OpenMenu__MAIN_DEFAULT, 128);
    lv_style_set_shadow_width(&GUI_Style__Button__MENU__OpenMenu__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__MENU__OpenMenu__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__MENU__OpenMenu__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__MENU__OpenMenu__MAIN_DEFAULT, 2);
    lv_obj_add_style(GUI_Button__MENU__OpenMenu, &GUI_Style__Button__MENU__OpenMenu__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__MENU__Button__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__MENU__Button__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__MENU__Button__MAIN_DEFAULT, lv_color_make(33, 158, 242));
    lv_style_set_bg_opa(&GUI_Style__Button__MENU__Button__MAIN_DEFAULT, 66);
    lv_style_set_radius(&GUI_Style__Button__MENU__Button__MAIN_DEFAULT, 90);
    lv_style_set_shadow_color(&GUI_Style__Button__MENU__Button__MAIN_DEFAULT, lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__MENU__Button__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__MENU__Button__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__MENU__Button__MAIN_DEFAULT, 2);
    lv_style_set_shadow_width(&GUI_Style__Button__MENU__Button__MAIN_DEFAULT, 2);
    lv_style_set_shadow_spread(&GUI_Style__Button__MENU__Button__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__MENU__Button, &GUI_Style__Button__MENU__Button__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);
}
