// This file was generated by SquareLine Vision Exporter
// Project name: PIAM Pro

#include "../GUI.h"

void GUI_initScreen__PIAMSYS() {
    GUI_Screen__PIAMSYS = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__PIAMSYS, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(GUI_Screen__PIAMSYS, GUI_event__Screen__PIAMSYS__Gesture_Top, LV_EVENT_GESTURE, NULL);
    GUI_Button__PIAMSYS__Button_1 = lv_button_create(GUI_Screen__PIAMSYS);
    lv_obj_set_align(GUI_Button__PIAMSYS__Button_1, LV_ALIGN_CENTER);
    lv_obj_set_x(GUI_Button__PIAMSYS__Button_1, -100);
    lv_obj_set_size(GUI_Button__PIAMSYS__Button_1, 110, 252);

    GUI_Button__PIAMSYS__Button_2 = lv_button_create(GUI_Screen__PIAMSYS);
    lv_obj_set_align(GUI_Button__PIAMSYS__Button_2, LV_ALIGN_CENTER);
    lv_obj_set_x(GUI_Button__PIAMSYS__Button_2, 100);
    lv_obj_set_size(GUI_Button__PIAMSYS__Button_2, 110, 252);

    GUI_initScreenStyles__PIAMSYS();
    GUI_initScreenTexts__PIAMSYS();
}

void GUI_initScreenTexts__PIAMSYS() {
}

void GUI_initScreenStyles__PIAMSYS() {
    static lv_style_t GUI_Style__Screen__PIAMSYS__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Screen__PIAMSYS__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Screen__PIAMSYS__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Screen__PIAMSYS__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Screen__PIAMSYS__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Screen__PIAMSYS, &GUI_Style__Screen__PIAMSYS__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__PIAMSYS__Button_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__PIAMSYS__Button_1__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__PIAMSYS__Button_1__MAIN_DEFAULT, lv_color_make(216, 104, 0));
    lv_style_set_bg_opa(&GUI_Style__Button__PIAMSYS__Button_1__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__PIAMSYS__Button_1__MAIN_DEFAULT, 10);
    lv_obj_add_style(GUI_Button__PIAMSYS__Button_1, &GUI_Style__Button__PIAMSYS__Button_1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__PIAMSYS__Button_2__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__PIAMSYS__Button_2__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__PIAMSYS__Button_2__MAIN_DEFAULT, lv_color_make(0, 78, 247));
    lv_style_set_bg_opa(&GUI_Style__Button__PIAMSYS__Button_2__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__PIAMSYS__Button_2__MAIN_DEFAULT, 10);
    lv_obj_add_style(GUI_Button__PIAMSYS__Button_2, &GUI_Style__Button__PIAMSYS__Button_2__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);
}
