// This file was generated by SquareLine Vision Exporter
// Project name: PIAM Pro

#include "../GUI.h"

void GUI_initScreen__SOS() {
    GUI_Screen__SOS = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__SOS, LV_OBJ_FLAG_SCROLLABLE);

    GUI_initScreenStyles__SOS();
    GUI_initScreenTexts__SOS();
}

void GUI_initScreenTexts__SOS() {
}

void GUI_initScreenStyles__SOS() {
    static lv_style_t GUI_Style__Screen__SOS__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Screen__SOS__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Screen__SOS__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Screen__SOS__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Screen__SOS__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Screen__SOS, &GUI_Style__Screen__SOS__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);
}
